{
    "items": [
        {
            "tags": [
                "macos",
                "icons",
                "nsbundle"
            ],
            "owner": {
                "reputation": 445,
                "user_id": 1079430,
                "user_type": "registered",
                "accept_rate": 74,
                "profile_image": "https://www.gravatar.com/avatar/6bf00489520e8f013752bac52318def2?s=128&d=identicon&r=PG",
                "display_name": "GuyGizmo",
                "link": "https://stackoverflow.com/users/1079430/guygizmo"
            },
            "is_answered": true,
            "view_count": 12,
            "accepted_answer_id": 50010178,
            "answer_count": 1,
            "score": 0,
            "last_activity_date": 1524601250,
            "creation_date": 1524518694,
            "question_id": 49990220,
            "body_markdown": "If I have the full path of an application&#39;s bundle or an `NSBundle` instance for that application, how can I get an `NSImage` representation of that app&#39;s icon?\r\n\r\nSpecifically, I&#39;d like to get the best available version of the icon for a particular set of dimensions. For example, if the available versions of an app&#39;s icon include dimensions 32x32, 64x64, and 128x128 points, if I request one for 96x96 points I would get the 128x128 version.\r\n\r\nThis will need to work on both retina and non-retina displays, so the resulting `NSImage` will have to include both retina and non-retina representations of the icon.\r\n\r\nI&#39;ve found the `iconForFile:` method of `NSWorkspace` but unfortunately it only gives back a 32x32 pixel icon, so that&#39;s not useful for my purposes.\r\n\r\nI could also read in the bundle&#39;s `CFBundleIconFile` and `CFBundleIconName` keys from its info dictionary, and then pull the correct image from its icns file or assets catalog, but that seems like a lot of work. I&#39;m not sure where to begin with getting images from either of those file types. I hope there&#39;s an easier way!",
            "link": "https://stackoverflow.com/questions/49990220/given-the-full-path-or-an-nsbundle-instance-of-an-application-how-do-you-get-it",
            "title": "Given the full path or an NSBundle instance of an application, how do you get its icon?",
            "body": "<p>If I have the full path of an application's bundle or an <code>NSBundle</code> instance for that application, how can I get an <code>NSImage</code> representation of that app's icon?</p>\n\n<p>Specifically, I'd like to get the best available version of the icon for a particular set of dimensions. For example, if the available versions of an app's icon include dimensions 32x32, 64x64, and 128x128 points, if I request one for 96x96 points I would get the 128x128 version.</p>\n\n<p>This will need to work on both retina and non-retina displays, so the resulting <code>NSImage</code> will have to include both retina and non-retina representations of the icon.</p>\n\n<p>I've found the <code>iconForFile:</code> method of <code>NSWorkspace</code> but unfortunately it only gives back a 32x32 pixel icon, so that's not useful for my purposes.</p>\n\n<p>I could also read in the bundle's <code>CFBundleIconFile</code> and <code>CFBundleIconName</code> keys from its info dictionary, and then pull the correct image from its icns file or assets catalog, but that seems like a lot of work. I'm not sure where to begin with getting images from either of those file types. I hope there's an easier way!</p>\n"
        },
        {
            "tags": [
                "swift",
                "uiimage"
            ],
            "owner": {
                "reputation": 2568,
                "user_id": 468455,
                "user_type": "registered",
                "accept_rate": 57,
                "profile_image": "https://www.gravatar.com/avatar/89de137777d96d6dc5902388b4b1ba52?s=128&d=identicon&r=PG",
                "display_name": "PruitIgoe",
                "link": "https://stackoverflow.com/users/468455/pruitigoe"
            },
            "is_answered": true,
            "view_count": 22,
            "accepted_answer_id": 50009984,
            "answer_count": 2,
            "score": 0,
            "last_activity_date": 1524601238,
            "creation_date": 1524598848,
            "last_edit_date": 1524599868,
            "question_id": 50009644,
            "body_markdown": "I am trying to load a UIImage from a URL and then pass that UIImage back through a closure. \r\n\r\nThis is the code to get the image:\r\n\r\n    func getImageFromData(_ imgURL:URL, completion: @escaping imageClosure) {\r\n        \r\n        print(&quot;Download Started&quot;)\r\n        getDataFromUrl(url: imgURL) { data, response, error in\r\n            guard let data = data, error == nil else {\r\n                return\r\n            }\r\n            \r\n            if let thisImage = UIImage(data: data) {\r\n                completion(thisImage)\r\n            }\r\n            \r\n        }\r\n        \r\n    }\r\n    \r\n    func getDataFromUrl(url: URL, completion: @escaping (Data?, URLResponse?, Error?) -&gt; ()) {\r\n        URLSession.shared.dataTask(with: url) { data, response, error in\r\n            completion(data, response, error)\r\n            }.resume()\r\n    }\r\n\r\n this is imageClosure\r\n\r\n    typealias imageClosure = (_ thisImage:UIImage) -&gt; Void\r\n\r\nand I am calling as such\r\n\r\n    let thisImage:UIImage = myAPIManager.getImageFromData(thisImageURL, completion: { (thisImage:UIImage) in\r\n            \r\n        })\r\n\r\nand I get the error on the above line: \r\n\r\n    Cannot convert value of type &#39;()&#39; to specified type &#39;UIImage&#39;",
            "link": "https://stackoverflow.com/questions/50009644/cannot-convert-value-of-type-to-uiimage-swift",
            "title": "&quot;Cannot convert value of type &#39;()&#39; to UIImage&quot;: Swift",
            "body": "<p>I am trying to load a UIImage from a URL and then pass that UIImage back through a closure. </p>\n\n<p>This is the code to get the image:</p>\n\n<pre><code>func getImageFromData(_ imgURL:URL, completion: @escaping imageClosure) {\n\n    print(\"Download Started\")\n    getDataFromUrl(url: imgURL) { data, response, error in\n        guard let data = data, error == nil else {\n            return\n        }\n\n        if let thisImage = UIImage(data: data) {\n            completion(thisImage)\n        }\n\n    }\n\n}\n\nfunc getDataFromUrl(url: URL, completion: @escaping (Data?, URLResponse?, Error?) -&gt; ()) {\n    URLSession.shared.dataTask(with: url) { data, response, error in\n        completion(data, response, error)\n        }.resume()\n}\n</code></pre>\n\n<p>this is imageClosure</p>\n\n<pre><code>typealias imageClosure = (_ thisImage:UIImage) -&gt; Void\n</code></pre>\n\n<p>and I am calling as such</p>\n\n<pre><code>let thisImage:UIImage = myAPIManager.getImageFromData(thisImageURL, completion: { (thisImage:UIImage) in\n\n    })\n</code></pre>\n\n<p>and I get the error on the above line: </p>\n\n<pre><code>Cannot convert value of type '()' to specified type 'UIImage'\n</code></pre>\n"
        },
        {
            "tags": [
                "python",
                "string",
                "python-3.x",
                "pandas",
                "set"
            ],
            "owner": {
                "reputation": 330,
                "user_id": 5703997,
                "user_type": "registered",
                "accept_rate": 50,
                "profile_image": "https://www.gravatar.com/avatar/0bdab5bc5e1c92920a03d44a9a0278f9?s=128&d=identicon&r=PG&f=1",
                "display_name": "LMGagne",
                "link": "https://stackoverflow.com/users/5703997/lmgagne"
            },
            "is_answered": false,
            "view_count": 60,
            "answer_count": 0,
            "score": 0,
            "last_activity_date": 1524601200,
            "creation_date": 1524577751,
            "last_edit_date": 1524578257,
            "question_id": 50003383,
            "body_markdown": "I have a pandas dataframe that looks like this:\r\n\r\n    ORD\t                                                            Ideal \r\n    Humor / Laughter, Independent Work, Unclear Goals/Direction    Making A Difference, Seeing The Results Of My Effort, Honesty\r\n    Compassion Or Kindness, Positivity, Unclear Impact             Independent, Seeing The Results Of My Effort, Honesty\r\n    Making A Difference, Seeing The Results Of My Effort, Honesty  Making A Difference, Seeing The Results Of My Effort, Honesty\r\n\r\nI&#39;m trying to find the percent of overlap between the text in the two columns as a whole and also between each individual word/phrase.  Ideally, my output would look something like this:\r\n\r\n    ORD  Ideal match_perc ORD_0 ORD_1 ORD_2 Ideal_0 Ideal_1 Ideal_2 ORD_0_Match ORD_1_Match ORD_2_Match\r\n    text text  0          text  text  text  text    text    text    True       True         False\r\n\r\nI&#39;ve gotten part of the way there using the following to split apart the original 2 columns:\r\n\r\n    df= pd.concat([df[[&#39;ORD&#39;, &#39;Ideal&#39;]], df[&#39;ORD&#39;].str.split(&#39;, &#39;, expand=True)], axis=1)\r\n\r\nBut haven&#39;t found an efficient way to calculate the matches.  I tried to convert the columns to sets (using the code below) and then use `.intersection` but the conversion never works out the way I want.\r\n\r\n    df[&#39;ORD_set&#39;] = set(df[&#39;ORD&#39;])\r\n\r\nresults in the ORD_set column not being the same as the ORD column (an indexing issue?)\r\n\r\n    df[&#39;ORD_set&#39;] = df.apply(lambda x: set(df[&#39;ORD&#39;]))\r\n\r\nresults in NaN for every row\r\n\r\n    df.apply(lambda x: set(df[&#39;ORD&#39;]).intersection(set(df[&#39;Ideal&#39;])))\r\n\r\nresults in `{}` for every row\r\n\r\nIs this the most efficient way to find the match rate?  If so, how can I fix this set issue?\r\n",
            "link": "https://stackoverflow.com/questions/50003383/comparing-multiple-strings-out-of-order",
            "title": "Comparing multiple strings out of order",
            "body": "<p>I have a pandas dataframe that looks like this:</p>\n\n<pre><code>ORD                                                             Ideal \nHumor / Laughter, Independent Work, Unclear Goals/Direction    Making A Difference, Seeing The Results Of My Effort, Honesty\nCompassion Or Kindness, Positivity, Unclear Impact             Independent, Seeing The Results Of My Effort, Honesty\nMaking A Difference, Seeing The Results Of My Effort, Honesty  Making A Difference, Seeing The Results Of My Effort, Honesty\n</code></pre>\n\n<p>I'm trying to find the percent of overlap between the text in the two columns as a whole and also between each individual word/phrase.  Ideally, my output would look something like this:</p>\n\n<pre><code>ORD  Ideal match_perc ORD_0 ORD_1 ORD_2 Ideal_0 Ideal_1 Ideal_2 ORD_0_Match ORD_1_Match ORD_2_Match\ntext text  0          text  text  text  text    text    text    True       True         False\n</code></pre>\n\n<p>I've gotten part of the way there using the following to split apart the original 2 columns:</p>\n\n<pre><code>df= pd.concat([df[['ORD', 'Ideal']], df['ORD'].str.split(', ', expand=True)], axis=1)\n</code></pre>\n\n<p>But haven't found an efficient way to calculate the matches.  I tried to convert the columns to sets (using the code below) and then use <code>.intersection</code> but the conversion never works out the way I want.</p>\n\n<pre><code>df['ORD_set'] = set(df['ORD'])\n</code></pre>\n\n<p>results in the ORD_set column not being the same as the ORD column (an indexing issue?)</p>\n\n<pre><code>df['ORD_set'] = df.apply(lambda x: set(df['ORD']))\n</code></pre>\n\n<p>results in NaN for every row</p>\n\n<pre><code>df.apply(lambda x: set(df['ORD']).intersection(set(df['Ideal'])))\n</code></pre>\n\n<p>results in <code>{}</code> for every row</p>\n\n<p>Is this the most efficient way to find the match rate?  If so, how can I fix this set issue?</p>\n"
        },
        {
            "tags": [
                "firebase"
            ],
            "owner": {
                "reputation": 43,
                "user_id": 496449,
                "user_type": "registered",
                "profile_image": "https://www.gravatar.com/avatar/5c93aa5ffe22a904e827f6718e6ca7b5?s=128&d=identicon&r=PG",
                "display_name": "Marcin Trofimiuk",
                "link": "https://stackoverflow.com/users/496449/marcin-trofimiuk"
            },
            "is_answered": false,
            "view_count": 14,
            "answer_count": 0,
            "score": 0,
            "last_activity_date": 1524601193,
            "creation_date": 1524601193,
            "question_id": 50010167,
            "body_markdown": "Tried to create firebase project adding my existing Google Cloud project. It failed after last step:\r\n[![enter image description here][1]][1]\r\n\r\nIt fails at this request which ends with `500` status code:\r\n\r\n`POST https://mobilesdk-pa.clients6.google.com/v1/projects:migrateToFirebaseProject?key=XXXXX_REMOVED_XXXXX&amp;alt=json`\r\n\r\n\r\n```\r\n{\r\n  &quot;error&quot;: {\r\n    &quot;code&quot;: 500,\r\n    &quot;message&quot;: &quot;2: \\u003ceye3 title=&#39;/ThirdPartyFederatedService.SetOAuthAppConfig, INVALID_ARGUMENT&#39;/\\u003e APPLICATION_ERROR;apps.auth.proto/ThirdPartyFederatedService.SetOAuthAppConfig;client_id cannot be empty for provider: yahoo\\ncom.google.net.rpc3.RpcException: OpenAuth::INPUT_ERROR: client_id cannot be empty for provider: yahoo  \r\n[REMOVED quite long stack trace here]&quot;,\r\n    &quot;status&quot;: &quot;UNKNOWN&quot;,\r\n    &quot;details&quot;: [\r\n      {\r\n        &quot;@type&quot;: &quot;type.googleapis.com/google.internal.firebase.v1.ErrorCode&quot;\r\n      }\r\n    ]\r\n  }\r\n}\r\n```\r\n\r\n\r\n  [1]: https://i.stack.imgur.com/GnWXS.png",
            "link": "https://stackoverflow.com/questions/50010167/cannot-create-firebase-project-error-at-v1-projectsmigratetofirebaseproject",
            "title": "Cannot create firebase project error at /v1/projects:migrateToFirebaseProject",
            "body": "<p>Tried to create firebase project adding my existing Google Cloud project. It failed after last step:\n<a href=\"https://i.stack.imgur.com/GnWXS.png\" rel=\"nofollow noreferrer\"><img src=\"https://i.stack.imgur.com/GnWXS.png\" alt=\"enter image description here\"></a></p>\n\n<p>It fails at this request which ends with <code>500</code> status code:</p>\n\n<p><code>POST https://mobilesdk-pa.clients6.google.com/v1/projects:migrateToFirebaseProject?key=XXXXX_REMOVED_XXXXX&amp;alt=json</code></p>\n\n<p><code>\n{\n  \"error\": {\n    \"code\": 500,\n    \"message\": \"2: \\u003ceye3 title='/ThirdPartyFederatedService.SetOAuthAppConfig, INVALID_ARGUMENT'/\\u003e APPLICATION_ERROR;apps.auth.proto/ThirdPartyFederatedService.SetOAuthAppConfig;client_id cannot be empty for provider: yahoo\\ncom.google.net.rpc3.RpcException: OpenAuth::INPUT_ERROR: client_id cannot be empty for provider: yahoo<br>\n[REMOVED quite long stack trace here]\",\n    \"status\": \"UNKNOWN\",\n    \"details\": [\n      {\n        \"@type\": \"type.googleapis.com/google.internal.firebase.v1.ErrorCode\"\n      }\n    ]\n  }\n}\n</code></p>\n"
        },
        {
            "tags": [
                "sql",
                "vb.net",
                "ms-access"
            ],
            "owner": {
                "reputation": 59,
                "user_id": 6923139,
                "user_type": "registered",
                "accept_rate": 47,
                "profile_image": "https://www.gravatar.com/avatar/c4f55643b357a8a86f6c54263ea56301?s=128&d=identicon&r=PG&f=1",
                "display_name": "programer Anel",
                "link": "https://stackoverflow.com/users/6923139/programer-anel"
            },
            "is_answered": false,
            "view_count": 42,
            "closed_date": 1524609772,
            "answer_count": 0,
            "score": 0,
            "last_activity_date": 1524601182,
            "creation_date": 1524600915,
            "last_edit_date": 1524601182,
            "question_id": 50010102,
            "body_markdown": "With below code, I run the update on a specific table. The query completes without any problems (exception) but results are not updated in table. How is this even possible?\r\n\r\nTable structure\r\n\r\n[![enter image description here][1]][1]\r\n\r\nUpdate query\r\n\r\n&lt;!-- language: vb --&gt;\r\n\r\n     Dim cmd As New OleDb.OleDbCommand\r\n            cmd.CommandText = &quot; UPDATE  [leadsonline_stores] SET [db_Path] = @db_Path,[Image_Path] = @Image_Path,[lo_Username] = @lo_Username,[lo_Password] = @lo_Password,[lo_Store] = @lo_Store,[Notes] = @Notes,[lo_Active] = @lo_Active WHERE [ID] = @ID &quot;\r\n\r\n            cmd.Connection = dbMain\r\n\r\n            With cmd.Parameters\r\n                .AddWithValue(&quot;@ID&quot;, leadsonline_stores_ID)\r\n                .AddWithValue(&quot;@db_Path&quot;, txtDatabase.Text)\r\n                .AddWithValue(&quot;@Image_Path&quot;, txtPath.Text)\r\n                .AddWithValue(&quot;@lo_Username&quot;, txtUsername.Text)\r\n                .AddWithValue(&quot;@lo_Password&quot;, txtPassword.Text)\r\n                .AddWithValue(&quot;@lo_Store&quot;, txtStoreId.Text)\r\n                .AddWithValue(&quot;@Notes&quot;, txtDescription.Text)\r\n                .AddWithValue(&quot;@lo_Active&quot;, IIf(IsNothing(chkActive.EditValue), DBNull.Value, chkActive.EditValue))\r\n            End With\r\n\r\n            Try\r\n\r\n                cmd.ExecuteNonQuery()\r\n\r\n            Catch ex As Exception\r\n                MessageBox.Show(&quot;Error while changing data&quot;, &quot;Message&quot;, MessageBoxButtons.OK, MessageBoxIcon.Exclamation)\r\n                dbMain.Close()\r\n                Return False\r\n            End Try\r\n\r\n\r\nBefore update : \r\n\r\n[![enter image description here][2]][2]\r\n\r\nDebugger info :\r\n[![enter image description here][3]][3]\r\n\r\nWhat am i missing here.\r\n\r\n  [1]: https://i.stack.imgur.com/LXlxi.png\r\n  [2]: https://i.stack.imgur.com/4UPfC.png\r\n  [3]: https://i.stack.imgur.com/prrTF.png",
            "link": "https://stackoverflow.com/questions/50010102/ms-access-simple-sql-update-query",
            "closed_reason": "duplicate",
            "title": "MS Access simple SQL update query",
            "body": "<p>With below code, I run the update on a specific table. The query completes without any problems (exception) but results are not updated in table. How is this even possible?</p>\n\n<p>Table structure</p>\n\n<p><a href=\"https://i.stack.imgur.com/LXlxi.png\" rel=\"nofollow noreferrer\"><img src=\"https://i.stack.imgur.com/LXlxi.png\" alt=\"enter image description here\"></a></p>\n\n<p>Update query</p>\n\n<pre class=\"lang-vb prettyprint-override\"><code> Dim cmd As New OleDb.OleDbCommand\n        cmd.CommandText = \" UPDATE  [leadsonline_stores] SET [db_Path] = @db_Path,[Image_Path] = @Image_Path,[lo_Username] = @lo_Username,[lo_Password] = @lo_Password,[lo_Store] = @lo_Store,[Notes] = @Notes,[lo_Active] = @lo_Active WHERE [ID] = @ID \"\n\n        cmd.Connection = dbMain\n\n        With cmd.Parameters\n            .AddWithValue(\"@ID\", leadsonline_stores_ID)\n            .AddWithValue(\"@db_Path\", txtDatabase.Text)\n            .AddWithValue(\"@Image_Path\", txtPath.Text)\n            .AddWithValue(\"@lo_Username\", txtUsername.Text)\n            .AddWithValue(\"@lo_Password\", txtPassword.Text)\n            .AddWithValue(\"@lo_Store\", txtStoreId.Text)\n            .AddWithValue(\"@Notes\", txtDescription.Text)\n            .AddWithValue(\"@lo_Active\", IIf(IsNothing(chkActive.EditValue), DBNull.Value, chkActive.EditValue))\n        End With\n\n        Try\n\n            cmd.ExecuteNonQuery()\n\n        Catch ex As Exception\n            MessageBox.Show(\"Error while changing data\", \"Message\", MessageBoxButtons.OK, MessageBoxIcon.Exclamation)\n            dbMain.Close()\n            Return False\n        End Try\n</code></pre>\n\n<p>Before update : </p>\n\n<p><a href=\"https://i.stack.imgur.com/4UPfC.png\" rel=\"nofollow noreferrer\"><img src=\"https://i.stack.imgur.com/4UPfC.png\" alt=\"enter image description here\"></a></p>\n\n<p>Debugger info :\n<a href=\"https://i.stack.imgur.com/prrTF.png\" rel=\"nofollow noreferrer\"><img src=\"https://i.stack.imgur.com/prrTF.png\" alt=\"enter image description here\"></a></p>\n\n<p>What am i missing here.</p>\n"
        },
        {
            "tags": [
                "javascript",
                "html"
            ],
            "owner": {
                "reputation": 26,
                "user_id": 8770543,
                "user_type": "registered",
                "accept_rate": 29,
                "profile_image": "https://lh6.googleusercontent.com/-R7bLZk726eg/AAAAAAAAAAI/AAAAAAAAAA8/vozcN6NyGd0/photo.jpg?sz=128",
                "display_name": "Simon Dean",
                "link": "https://stackoverflow.com/users/8770543/simon-dean"
            },
            "is_answered": true,
            "view_count": 26,
            "accepted_answer_id": 50010162,
            "answer_count": 2,
            "score": 0,
            "last_activity_date": 1524601179,
            "creation_date": 1524599417,
            "question_id": 50009751,
            "body_markdown": "I am attempting to return the target event id cell index. \r\n\r\nWhen I console log the output to test and pass in a static value for the target elements ID I am able to access the property fine, however, when I attempt to pass in the ID using the event object it returns undefined. \r\n\r\nI am attempting to do this so I can then iterate over all rows of the cell, but only at the cellIndex position of each loop. \r\n\r\nNote, the solution must be pure Javascript. \r\n\r\n    checkColWinFunc(target); \r\n    \r\n    function checkRowWinFunc(target) {\r\n    \r\n    var colEleNum = document.getElementById(target); \r\n    var colIndex = target.cellIndex; \r\n        \r\n    console.log(colIndex);   \r\n    \r\n    //Below loop for when index is accessible.   \r\n    //grabbing tables element by ID.     \r\n    // var topRow = document.getElementById(&quot;gameSpace&quot;); \r\n        \r\n        /*\r\n          for (x = 0; x &lt;= 4 ;x++){\r\n              console.log(colIndex); \r\n             }\r\n        */\r\n    }",
            "link": "https://stackoverflow.com/questions/50009751/unable-to-access-cellindex-when-passing-in-event-target-id-js",
            "title": "unable to access cellIndex when passing in event Target ID JS",
            "body": "<p>I am attempting to return the target event id cell index. </p>\n\n<p>When I console log the output to test and pass in a static value for the target elements ID I am able to access the property fine, however, when I attempt to pass in the ID using the event object it returns undefined. </p>\n\n<p>I am attempting to do this so I can then iterate over all rows of the cell, but only at the cellIndex position of each loop. </p>\n\n<p>Note, the solution must be pure Javascript. </p>\n\n<pre><code>checkColWinFunc(target); \n\nfunction checkRowWinFunc(target) {\n\nvar colEleNum = document.getElementById(target); \nvar colIndex = target.cellIndex; \n\nconsole.log(colIndex);   \n\n//Below loop for when index is accessible.   \n//grabbing tables element by ID.     \n// var topRow = document.getElementById(\"gameSpace\"); \n\n    /*\n      for (x = 0; x &lt;= 4 ;x++){\n          console.log(colIndex); \n         }\n    */\n}\n</code></pre>\n"
        },
        {
            "tags": [
                "shell",
                "unix",
                "error-handling",
                "exception-handling"
            ],
            "owner": {
                "reputation": 50,
                "user_id": 6139421,
                "user_type": "registered",
                "accept_rate": 11,
                "profile_image": "https://www.gravatar.com/avatar/dee1be76dd59901800d1e820fff0b9b9?s=128&d=identicon&r=PG&f=1",
                "display_name": "sk7979",
                "link": "https://stackoverflow.com/users/6139421/sk7979"
            },
            "is_answered": false,
            "view_count": 15,
            "answer_count": 1,
            "score": 0,
            "last_activity_date": 1524601177,
            "creation_date": 1524581550,
            "last_edit_date": 1524581726,
            "question_id": 50004731,
            "body_markdown": "I have a code module in which I will be checking for errors using the `$`? in shell scripting. Assume the following scenario:\r\n\r\n    &quot;sub_script.sh&quot;\r\n    --error statements--\r\n    echo &quot;abc&quot;\r\n    \r\n    &quot;main_script.sh&quot;\r\n    sh sub_script.sh\r\n    if [ $? == 0 ];then\r\n     echo &quot;no error&quot;\r\n    else\r\n     echo &quot;error&quot;\r\n    fi\r\n\r\nNow, even if I have error statements in the `sub_script.sh` if I trigger the script from the `main_script.sh` I can&#39;t handle it because I have an `echo` statement which runs successfully and returns 0 value.\r\n\r\nI just replicated this here I have many shell scripts which run a hive or spark or some other code.\r\n\r\nIs there any change to handle this kind of scenario in shell scripting?\r\n\r\nThanks in advance!\r\n",
            "link": "https://stackoverflow.com/questions/50004731/handling-exceptions-or-errors-in-shell-scripting",
            "title": "handling exceptions or errors in shell scripting",
            "body": "<p>I have a code module in which I will be checking for errors using the \"$?\" in shell scripting. Assume the following scenario:</p>\n\n<pre><code>\"sub_script.sh\"\n--error statements--\necho \"abc\"\n\n\"main_script.sh\"\nsh sub_script.sh\nif [ $? == 0 ];then\n echo \"no error\"\nelse\n echo \"error\"\nfi\n</code></pre>\n\n<p>Now, even if I have error statements in the <code>sub_script.sh</code> if I trigger the script from the <code>main_script.sh</code> I can't handle it because I have an <code>echo</code> statement which runs successfully and returns 0 value.</p>\n\n<p>I just replicated this here I have many shell scripts which run a hive or spark or some other code.</p>\n\n<p>Is there any change to handle this kind of scenario in shell scripting?</p>\n\n<p>Thanks in advance!</p>\n"
        },
        {
            "tags": [
                "hibernate",
                "hibernate-criteria"
            ],
            "owner": {
                "reputation": 153,
                "user_id": 2962555,
                "user_type": "registered",
                "accept_rate": 44,
                "profile_image": "https://www.gravatar.com/avatar/f2fa1a1ceefbb11d49af0d465dc742fa?s=128&d=identicon&r=PG&f=1",
                "display_name": "Laodao",
                "link": "https://stackoverflow.com/users/2962555/laodao"
            },
            "is_answered": false,
            "view_count": 11,
            "answer_count": 0,
            "score": 0,
            "last_activity_date": 1524601165,
            "creation_date": 1524600112,
            "last_edit_date": 1524601165,
            "question_id": 50009917,
            "body_markdown": "I have two entities are many-to-many relationship as below:\r\n\r\n    @Entity\r\n    @Table(name = &quot;table_a&quot;)\r\n    @JsonIgnoreProperties({&quot;hibernateLazyInitializer&quot;, &quot;handler&quot;})\r\n    @DynamicUpdate\r\n    @DynamicInsert\r\n    public class EntityA implements Serializable {\r\n    \r\n    \tprivate static final long serialVersionUID = -1L;\r\n    \r\n    \tprivate int id;\r\n    \tprivate String aKey;\r\n    \tprivate Set&lt;EntityB&gt; bList;\r\n    \r\n    \t@Id\r\n    \t@GeneratedValue\r\n    \t@Column(name = &quot;id&quot;)\r\n    \tpublic int getId() {\r\n    \t\treturn id;\r\n    \t}\r\n    \r\n    \tpublic void setId(int id) {\r\n    \t\tthis.id = id;\r\n    \t}\r\n    \r\n    \t@Column(name = &quot;a_key&quot;)\r\n    \tpublic String getAKey() {\r\n    \t\treturn aKey;\r\n    \t}\r\n    \r\n    \tpublic void setAKey(String aKey) {\r\n    \t\tthis.aKey = aKey;\r\n    \t}\r\n    \r\n    \t@ManyToMany(cascade = CascadeType.PERSIST)\r\n    \t@JoinTable(name = &quot;a_b&quot;, joinColumns = @JoinColumn(name = &quot;a_key&quot;, referencedColumnName = &quot;a_key&quot;), inverseJoinColumns = @JoinColumn(name = &quot;b_key&quot;, referencedColumnName = &quot;b_key&quot;))\r\n    \tpublic Set&lt;EntityB&gt; getBList() {\r\n    \t\treturn bList;\r\n    \t}\r\n    \r\n    \tpublic void setbList(Set&lt;EntityB&gt; bList) {\r\n    \t\tthis.bList = bList;\r\n    \t}\r\n    \r\n    }\r\n\r\nand \r\n\r\n    @Entity\r\n    @Table(name = &quot;table_b&quot;)\r\n    @JsonIgnoreProperties({&quot;hibernateLazyInitializer&quot;, &quot;handler&quot;})\r\n    @DynamicUpdate\r\n    @DynamicInsert\r\n    public class EntityB implements Serializable {\r\n    \r\n    \tprivate static final long serialVersionUID = -1L;\r\n    \r\n    \tprivate int id;\r\n    \tprivate String bKey;\r\n    \tprivate Set&lt;EntityC&gt; cList;\r\n    \r\n    \t@Id\r\n    \t@GeneratedValue\r\n    \t@Column(name = &quot;id&quot;)\r\n    \tpublic int getId() {\r\n    \t\treturn id;\r\n    \t}\r\n    \r\n    \tpublic void setId(int id) {\r\n    \t\tthis.id = id;\r\n    \t}\r\n    \r\n    \t@Column(name = &quot;b_key&quot;)\r\n    \tpublic String getBKey() {\r\n    \t\treturn bKey;\r\n    \t}\r\n    \r\n    \tpublic void setBKey(String bKey) {\r\n    \t\tthis.bKey = bKey;\r\n    \t}\r\n    \r\n        @JsonManagedReference(value = &quot;b_c&quot;)\r\n        @OneToMany(mappedBy = &quot;b&quot;, cascade = CascadeType.PERSIST)\r\n        public Set&lt;EntityC&gt; getCList() {\r\n            return cList;\r\n        }\r\n    \r\n        public void setCList(Set&lt;EntityC&gt; cList) {\r\n            this.cList = cList;\r\n        }\r\n    \r\n    }\r\n\r\nNow, when I do following, \r\n\r\n            Session session = entityManager.unwrap(Session.class);\r\n            Criteria criteria = session.createCriteria(EntityA.class, &quot;a_alias&quot;);\r\n            criteria.createAlias(&quot;a_alias.bList&quot;, &quot;b_alias&quot;, JoinType.LEFT_OUTER_JOIN);\r\n            criteria.createAlias(&quot;b_alias.cList&quot;, &quot;c_alias&quot;, JoinType.LEFT_OUTER_JOIN);\r\n    \r\n            critier.add(Restrictions.eq(&quot;c_alias.name&quot;, &quot;abc&quot;));\r\n            return (List&lt;EntityA&gt;)criteria.list();\r\n\r\nI got Entity A correctly returned but with an empty list of Entity B. Am I missing something? Cause I expect one record in table_b that should be fetched. Hence, I turned on the show_sql and the sql returns me one record with corresponding values of table_b. Also, if I put a `Projections.property(&quot;b_alias.id&quot;)` to the Criteria, I actually get it returned. Please help. Thanks.\r\n",
            "link": "https://stackoverflow.com/questions/50009917/hibernate-criteria-get-many-to-many-field-always-empty-set",
            "title": "Hibernate Criteria get many-to-many field always empty set",
            "body": "<p>I have two entities are many-to-many relationship as below:</p>\n\n<pre><code>@Entity\n@Table(name = \"table_a\")\n@JsonIgnoreProperties({\"hibernateLazyInitializer\", \"handler\"})\n@DynamicUpdate\n@DynamicInsert\npublic class EntityA implements Serializable {\n\n    private static final long serialVersionUID = -1L;\n\n    private int id;\n    private String aKey;\n    private Set&lt;EntityB&gt; bList;\n\n    @Id\n    @GeneratedValue\n    @Column(name = \"id\")\n    public int getId() {\n        return id;\n    }\n\n    public void setId(int id) {\n        this.id = id;\n    }\n\n    @Column(name = \"a_key\")\n    public String getAKey() {\n        return aKey;\n    }\n\n    public void setAKey(String aKey) {\n        this.aKey = aKey;\n    }\n\n    @ManyToMany(cascade = CascadeType.PERSIST)\n    @JoinTable(name = \"a_b\", joinColumns = @JoinColumn(name = \"a_key\", referencedColumnName = \"a_key\"), inverseJoinColumns = @JoinColumn(name = \"b_key\", referencedColumnName = \"b_key\"))\n    public Set&lt;EntityB&gt; getBList() {\n        return bList;\n    }\n\n    public void setbList(Set&lt;EntityB&gt; bList) {\n        this.bList = bList;\n    }\n\n}\n</code></pre>\n\n<p>and </p>\n\n<pre><code>@Entity\n@Table(name = \"table_b\")\n@JsonIgnoreProperties({\"hibernateLazyInitializer\", \"handler\"})\n@DynamicUpdate\n@DynamicInsert\npublic class EntityB implements Serializable {\n\n    private static final long serialVersionUID = -1L;\n\n    private int id;\n    private String bKey;\n    private Set&lt;EntityC&gt; cList;\n\n    @Id\n    @GeneratedValue\n    @Column(name = \"id\")\n    public int getId() {\n        return id;\n    }\n\n    public void setId(int id) {\n        this.id = id;\n    }\n\n    @Column(name = \"b_key\")\n    public String getBKey() {\n        return bKey;\n    }\n\n    public void setBKey(String bKey) {\n        this.bKey = bKey;\n    }\n\n    @JsonManagedReference(value = \"b_c\")\n    @OneToMany(mappedBy = \"b\", cascade = CascadeType.PERSIST)\n    public Set&lt;EntityC&gt; getCList() {\n        return cList;\n    }\n\n    public void setCList(Set&lt;EntityC&gt; cList) {\n        this.cList = cList;\n    }\n\n}\n</code></pre>\n\n<p>Now, when I do following, </p>\n\n<pre><code>        Session session = entityManager.unwrap(Session.class);\n        Criteria criteria = session.createCriteria(EntityA.class, \"a_alias\");\n        criteria.createAlias(\"a_alias.bList\", \"b_alias\", JoinType.LEFT_OUTER_JOIN);\n        criteria.createAlias(\"b_alias.cList\", \"c_alias\", JoinType.LEFT_OUTER_JOIN);\n\n        critier.add(Restrictions.eq(\"c_alias.name\", \"abc\"));\n        return (List&lt;EntityA&gt;)criteria.list();\n</code></pre>\n\n<p>I got Entity A correctly returned but with an empty list of Entity B. Am I missing something? Cause I expect one record in table_b that should be fetched. Hence, I turned on the show_sql and the sql returns me one record with corresponding values of table_b. Also, if I put a <code>Projections.property(\"b_alias.id\")</code> to the Criteria, I actually get it returned. Please help. Thanks.</p>\n"
        },
        {
            "tags": [
                "php",
                "oracle"
            ],
            "owner": {
                "reputation": 3,
                "user_id": 3216926,
                "user_type": "registered",
                "accept_rate": 50,
                "profile_image": "https://www.gravatar.com/avatar/ac7b73d742a98f9f1171002c122772fc?s=128&d=identicon&r=PG&f=1",
                "display_name": "user3216926",
                "link": "https://stackoverflow.com/users/3216926/user3216926"
            },
            "is_answered": false,
            "view_count": 40,
            "answer_count": 0,
            "score": 0,
            "last_activity_date": 1524601165,
            "creation_date": 1524596271,
            "last_edit_date": 1524601165,
            "question_id": 50009020,
            "body_markdown": "I am trying to insert into an Oracle table from PHP a string containing single or double quote. **&quot;Test&quot;** or **Test&#39;s**\r\n\r\nI am using oci8 and oci_bind_by_name to bind values.\r\n\r\n    oci_bind_by_name($stmt, &#39;:hName&#39;, $value);\r\n\r\nI also tried specify the defaults:\r\n\r\n    oci_bind_by_name($stmt, &#39;:hName&#39;, $value, -1, SQLT_CHR);\r\n\r\nI tried PHP function before send it like:\r\n\r\n    addslashes();\r\n    str_replace(&quot;&#39;&quot;, &quot;&#39;&#39;&quot;, $string);  //To scape single quotes.\r\n\r\nBut every time I look the table the string has this value: \r\n\r\n    &amp;#34;Test&amp;#34;\r\n\r\nWhen I insert from SQL Developer\r\n\r\n    INSERT INTO table (notes) VALUES (:notes);\r\n\r\nSQL Developer prompt to enter *notes* value, I enter *&quot;Test&quot;* and when I look this new inserted row the value is correct with double quote: \r\n\r\n    &quot;Test&quot;\r\n\r\nAnd no like the PHP \r\n\r\n     &amp;#34;Test&amp;#34;\r\n\r\nThanks in advance.\r\n\r\n\r\n[SQL Developer result screenshot][1]\r\n\r\n\r\n  [1]: https://i.stack.imgur.com/5siwA.jpg",
            "link": "https://stackoverflow.com/questions/50009020/insert-string-with-quotes-into-oracle-with-php",
            "title": "Insert string with Quotes into Oracle with PHP",
            "body": "<p>I am trying to insert into an Oracle table from PHP a string containing single or double quote. <strong>\"Test\"</strong> or <strong>Test's</strong></p>\n\n<p>I am using oci8 and oci_bind_by_name to bind values.</p>\n\n<pre><code>oci_bind_by_name($stmt, ':hName', $value);\n</code></pre>\n\n<p>I also tried specify the defaults:</p>\n\n<pre><code>oci_bind_by_name($stmt, ':hName', $value, -1, SQLT_CHR);\n</code></pre>\n\n<p>I tried PHP function before send it like:</p>\n\n<pre><code>addslashes();\nstr_replace(\"'\", \"''\", $string);  //To scape single quotes.\n</code></pre>\n\n<p>But every time I look the table the string has this value: </p>\n\n<pre><code>&amp;#34;Test&amp;#34;\n</code></pre>\n\n<p>When I insert from SQL Developer</p>\n\n<pre><code>INSERT INTO table (notes) VALUES (:notes);\n</code></pre>\n\n<p>SQL Developer prompt to enter <em>notes</em> value, I enter <em>\"Test\"</em> and when I look this new inserted row the value is correct with double quote: </p>\n\n<pre><code>\"Test\"\n</code></pre>\n\n<p>And no like the PHP </p>\n\n<pre><code> &amp;#34;Test&amp;#34;\n</code></pre>\n\n<p>Thanks in advance.</p>\n\n<p><a href=\"https://i.stack.imgur.com/5siwA.jpg\" rel=\"nofollow noreferrer\">SQL Developer result screenshot</a></p>\n"
        },
        {
            "tags": [
                "javascript",
                "reactjs",
                "addeventlistener"
            ],
            "owner": {
                "reputation": 652,
                "user_id": 8450582,
                "user_type": "registered",
                "accept_rate": 100,
                "profile_image": "https://www.gravatar.com/avatar/d5c1a1c036f2639af84a197be0554e0b?s=128&d=identicon&r=PG&f=1",
                "display_name": "Darren",
                "link": "https://stackoverflow.com/users/8450582/darren"
            },
            "is_answered": false,
            "view_count": 30,
            "answer_count": 0,
            "score": 0,
            "last_activity_date": 1524601155,
            "creation_date": 1524601155,
            "question_id": 50010159,
            "body_markdown": "I am trying to use `addEventListener` when the user `scroll` into view `&lt;div id=&quot;container&quot;&gt;`. I have done so by scroll height but my attempts to `addEventListener` when `&lt;div&gt;` is on the top of the window.\r\n\r\n    handleHeaderStuck = () =&gt; {\r\n        if (this.innerContainer.scrollTop &lt;= 500 &amp;&amp; this.state.isStuck === true) {\r\n            this.setState({isStuck: false});\r\n        }\r\n        else if (this.innerContainer.scrollTop &gt;= 500 &amp;&amp; this.state.isStuck !== true) {\r\n            this.setState({isStuck: true});\r\n        }\r\n    }\r\nThis will `setState` when scrolled `500px`.\r\n\r\n**How can I replace the condition of `500px` to be set when the user is with `id=&quot;container&quot;` as the top of the window? Also replace `isStuck` state to `isStuckBottom` when the user reaches the bottom of the div.**\r\n\r\nThe full code is\r\n\r\n    constructor(props) {\r\n        super(props)\r\n        this.state = {\r\n          isStuck: false,\r\n        }\r\n        this.handleHeaderStuck = this.handleHeaderStuck.bind(this)\r\n      }\r\n    \r\n      innerContainer = null\r\n    \r\n      componentDidMount () {\r\n        this.innerContainer.addEventListener(&quot;scroll&quot;, this.handleHeaderStuck);\r\n      }\r\n    \r\n      componentWillUnmount () {\r\n        this.innerContainer.removeEventListener(&quot;scroll&quot;, this.handleHeaderStuck);    \r\n      }\r\n\r\n      handleHeaderStuck = () =&gt; {\r\n         if (this.innerContainer.scrollTop &lt;= 500 &amp;&amp; this.state.isStuck === true) {\r\n            this.setState({isStuck: false});\r\n         }\r\n         else if (this.innerContainer.scrollTop &gt;= 500 &amp;&amp; this.state.isStuck !== true) {\r\n            this.setState({isStuck: true});\r\n         }\r\n      }\r\n\r\n\r\n \r\n\r\n",
            "link": "https://stackoverflow.com/questions/50010159/conditional-addeventlistener-when-div-id-is-at-top-of-window",
            "title": "Conditional addEventListener when div ID is at top of window",
            "body": "<p>I am trying to use <code>addEventListener</code> when the user <code>scroll</code> into view <code>&lt;div id=\"container\"&gt;</code>. I have done so by scroll height but my attempts to <code>addEventListener</code> when <code>&lt;div&gt;</code> is on the top of the window.</p>\n\n<pre><code>handleHeaderStuck = () =&gt; {\n    if (this.innerContainer.scrollTop &lt;= 500 &amp;&amp; this.state.isStuck === true) {\n        this.setState({isStuck: false});\n    }\n    else if (this.innerContainer.scrollTop &gt;= 500 &amp;&amp; this.state.isStuck !== true) {\n        this.setState({isStuck: true});\n    }\n}\n</code></pre>\n\n<p>This will <code>setState</code> when scrolled <code>500px</code>.</p>\n\n<p><strong>How can I replace the condition of <code>500px</code> to be set when the user is with <code>id=\"container\"</code> as the top of the window? Also replace <code>isStuck</code> state to <code>isStuckBottom</code> when the user reaches the bottom of the div.</strong></p>\n\n<p>The full code is</p>\n\n<pre><code>constructor(props) {\n    super(props)\n    this.state = {\n      isStuck: false,\n    }\n    this.handleHeaderStuck = this.handleHeaderStuck.bind(this)\n  }\n\n  innerContainer = null\n\n  componentDidMount () {\n    this.innerContainer.addEventListener(\"scroll\", this.handleHeaderStuck);\n  }\n\n  componentWillUnmount () {\n    this.innerContainer.removeEventListener(\"scroll\", this.handleHeaderStuck);    \n  }\n\n  handleHeaderStuck = () =&gt; {\n     if (this.innerContainer.scrollTop &lt;= 500 &amp;&amp; this.state.isStuck === true) {\n        this.setState({isStuck: false});\n     }\n     else if (this.innerContainer.scrollTop &gt;= 500 &amp;&amp; this.state.isStuck !== true) {\n        this.setState({isStuck: true});\n     }\n  }\n</code></pre>\n"
        },
        {
            "tags": [
                "html",
                "css",
                "width"
            ],
            "owner": {
                "reputation": 184,
                "user_id": 1110324,
                "user_type": "registered",
                "accept_rate": 100,
                "profile_image": "https://i.stack.imgur.com/FoXwa.png?s=128&g=1",
                "display_name": "Eddie",
                "link": "https://stackoverflow.com/users/1110324/eddie"
            },
            "is_answered": true,
            "view_count": 29,
            "answer_count": 3,
            "score": 1,
            "last_activity_date": 1524601147,
            "creation_date": 1524509041,
            "last_edit_date": 1524509613,
            "question_id": 49987941,
            "body_markdown": "This is a screenshot of a website with a screen width of 1000px:\r\n[![Screenshot 1000 width][1]][1]\r\n\r\nThis is a screenshot of *the same* website with a screen width of 460px&quot;\r\n[![enter image description here][2]][2]\r\n\r\nNotice in the first image, the unordered list is &quot;smaller&quot; than the table width. But in the second image, the unordered list is &quot;larger&quot; than the table width.\r\n\r\nThis is the website in question:\r\nhttp://www.practicalnetworking.net/subnet2.html\r\n\r\nI like the way the page looks on desktops (aka, the wider screenshot on top). But on mobile, the scale of everything seems off. The text is so much larger (relatively) than the text in the table.\r\n\r\nWhy is this happening?  How can I fix it so that both mobile and desktop websites look the same?\r\n\r\n*EDIT: The images were taken with Chrome&#39;s &quot;Screenshot&quot; tool in the Inspector. I did verify the behavior is consistent using my actual mobile phone though.*\r\n\r\n  [1]: https://i.stack.imgur.com/FdICI.png\r\n  [2]: https://i.stack.imgur.com/dPtQM.png",
            "link": "https://stackoverflow.com/questions/49987941/why-do-the-table-width-and-text-size-scale-differently-relative-to-each-other",
            "title": "Why do the table width and text size scale differently relative to each other?",
            "body": "<p>This is a screenshot of a website with a screen width of 1000px:\n<a href=\"https://i.stack.imgur.com/FdICI.png\" rel=\"nofollow noreferrer\"><img src=\"https://i.stack.imgur.com/FdICI.png\" alt=\"Screenshot 1000 width\"></a></p>\n\n<p>This is a screenshot of <em>the same</em> website with a screen width of 460px\"\n<a href=\"https://i.stack.imgur.com/dPtQM.png\" rel=\"nofollow noreferrer\"><img src=\"https://i.stack.imgur.com/dPtQM.png\" alt=\"enter image description here\"></a></p>\n\n<p>Notice in the first image, the unordered list is \"smaller\" than the table width. But in the second image, the unordered list is \"larger\" than the table width.</p>\n\n<p>This is the website in question:\n<a href=\"http://www.practicalnetworking.net/subnet2.html\" rel=\"nofollow noreferrer\">http://www.practicalnetworking.net/subnet2.html</a></p>\n\n<p>I like the way the page looks on desktops (aka, the wider screenshot on top). But on mobile, the scale of everything seems off. The text is so much larger (relatively) than the text in the table.</p>\n\n<p>Why is this happening?  How can I fix it so that both mobile and desktop websites look the same?</p>\n\n<p><em>EDIT: The images were taken with Chrome's \"Screenshot\" tool in the Inspector. I did verify the behavior is consistent using my actual mobile phone though.</em></p>\n"
        },
        {
            "tags": [
                "django",
                "image",
                "caching",
                "django-models"
            ],
            "owner": {
                "reputation": 22610,
                "user_id": 90025,
                "user_type": "registered",
                "accept_rate": 85,
                "profile_image": "https://www.gravatar.com/avatar/b3bb70a4bace7f9bd49f48b149ab95f9?s=128&d=identicon&r=PG",
                "display_name": "Paul Tarjan",
                "link": "https://stackoverflow.com/users/90025/paul-tarjan"
            },
            "is_answered": true,
            "view_count": 105145,
            "accepted_answer_id": 1793323,
            "answer_count": 22,
            "score": 207,
            "last_activity_date": 1524601135,
            "creation_date": 1251672987,
            "last_edit_date": 1251675809,
            "question_id": 1355150,
            "body_markdown": "In my model I have :\r\n\r\n    class Alias(MyBaseModel):\r\n        remote_image = models.URLField(max_length=500, null=True, help_text=&quot;A URL that is downloaded and cached for the image. Only\r\n     used when the alias is made&quot;)\r\n        image = models.ImageField(upload_to=&#39;alias&#39;, default=&#39;alias-default.png&#39;, help_text=&quot;An image representing the alias&quot;)\r\n\r\n        \r\n        def save(self, *args, **kw):\r\n            if (not self.image or self.image.name == &#39;alias-default.png&#39;) and self.remote_image :\r\n                try :\r\n                    data = utils.fetch(self.remote_image)\r\n                    image = StringIO.StringIO(data)\r\n                    image = Image.open(image)\r\n                    buf = StringIO.StringIO()\r\n                    image.save(buf, format=&#39;PNG&#39;)\r\n                    self.image.save(hashlib.md5(self.string_id).hexdigest() + &quot;.png&quot;, ContentFile(buf.getvalue()))\r\n                except IOError :\r\n                    pass\r\n\r\nWhich works great for the first time the `remote_image` changes. \r\n\r\nHow can I fetch a new image when someone has modified the `remote_image` on the alias? And secondly, is there a better way to cache a remote image?\r\n\r\n",
            "link": "https://stackoverflow.com/questions/1355150/django-when-saving-how-can-you-check-if-a-field-has-changed",
            "title": "Django: When saving, how can you check if a field has changed?",
            "body": "<p>In my model I have :</p>\n\n<pre><code>class Alias(MyBaseModel):\n    remote_image = models.URLField(max_length=500, null=True, help_text=\"A URL that is downloaded and cached for the image. Only\n used when the alias is made\")\n    image = models.ImageField(upload_to='alias', default='alias-default.png', help_text=\"An image representing the alias\")\n\n\n    def save(self, *args, **kw):\n        if (not self.image or self.image.name == 'alias-default.png') and self.remote_image :\n            try :\n                data = utils.fetch(self.remote_image)\n                image = StringIO.StringIO(data)\n                image = Image.open(image)\n                buf = StringIO.StringIO()\n                image.save(buf, format='PNG')\n                self.image.save(hashlib.md5(self.string_id).hexdigest() + \".png\", ContentFile(buf.getvalue()))\n            except IOError :\n                pass\n</code></pre>\n\n<p>Which works great for the first time the <code>remote_image</code> changes. </p>\n\n<p>How can I fetch a new image when someone has modified the <code>remote_image</code> on the alias? And secondly, is there a better way to cache a remote image?</p>\n"
        },
        {
            "tags": [
                "python-2.7",
                "google-cloud-platform",
                "google-bigquery",
                "client-library"
            ],
            "owner": {
                "reputation": 5,
                "user_id": 5228506,
                "user_type": "registered",
                "profile_image": "https://graph.facebook.com/834535513326199/picture?type=large",
                "display_name": "Swati Sneha",
                "link": "https://stackoverflow.com/users/5228506/swati-sneha"
            },
            "is_answered": true,
            "view_count": 34,
            "answer_count": 1,
            "score": 0,
            "last_activity_date": 1524601130,
            "creation_date": 1524470760,
            "question_id": 49976183,
            "body_markdown": "Can we connect to google cloud project, without using Client Library?\r\n\r\nWhat is `BigQuery API`? Is it similar to `bq-command line-tool`?\r\n\r\nIf not, is there any way to convert `bq-commandline-tool` to  API for usage in Pyhton?",
            "link": "https://stackoverflow.com/questions/49976183/is-there-any-way-to-connect-to-google-cloud-project-without-using-client-library",
            "title": "Is there any way to connect to google cloud project without using Client Library?",
            "body": "<p>Can we connect to google cloud project, without using Client Library?</p>\n\n<p>What is <code>BigQuery API</code>? Is it similar to <code>bq-command line-tool</code>?</p>\n\n<p>If not, is there any way to convert <code>bq-commandline-tool</code> to  API for usage in Pyhton?</p>\n"
        },
        {
            "tags": [
                "r",
                "tensorflow",
                "keras",
                "conv-neural-network",
                "transfer-learning"
            ],
            "owner": {
                "reputation": 70,
                "user_id": 7744356,
                "user_type": "registered",
                "profile_image": "https://i.stack.imgur.com/YRiBj.png?s=128&g=1",
                "display_name": "Bj&#246;rn",
                "link": "https://stackoverflow.com/users/7744356/bj%c3%b6rn"
            },
            "is_answered": true,
            "view_count": 33,
            "accepted_answer_id": 50003032,
            "answer_count": 1,
            "score": 0,
            "last_activity_date": 1524601126,
            "creation_date": 1524151173,
            "question_id": 49924675,
            "body_markdown": "Is there something really obvious that I am doing when trying to use the convolutional base from the XCeption architecture pre-trained on ImageNet? Here is my code that produces  the error at the end of the question:\r\n\r\n    require(keras)\r\n    \r\n    conv_base1 &lt;- application_xception(\r\n    weights = &quot;imagenet&quot;,\r\n    include_top = FALSE,\r\n    pooling=FALSE,\r\n    input_shape = c(300, 300, 3)\r\n    )\r\n    \r\n    model51 &lt;- keras_model_sequential() %&gt;%\r\n    conv_base1 %&gt;%\r\n    layer_flatten() %&gt;%\r\n    layer_dense(units = 256, activation = &quot;relu&quot;) %&gt;%\r\n    layer_dense(units = 1, activation = &quot;sigmoid&quot;)\r\n\r\nIn contrast, the almost identical code below using application_vgg16 works just fine:\r\n\r\n    require(keras)\r\n    \r\n    conv_base2 &lt;- application_vgg16(\r\n    weights = &quot;imagenet&quot;,\r\n    include_top = FALSE,\r\n    pooling=FALSE,\r\n    input_shape = c(300, 300, 3)\r\n    )\r\n    \r\n    model52 &lt;- keras_model_sequential() %&gt;%\r\n    conv_base2 %&gt;%\r\n    layer_flatten() %&gt;%\r\n    layer_dense(units = 2048, activation = &quot;relu&quot;) %&gt;%\r\n    layer_dense(units = 1, activation = &quot;sigmoid&quot;)\r\n\r\nI get the following errors (using R version 3.4.0 (2017-04-21) on Windows 10 x86_64-w64-mingw32/x64 (64-bit) using the keras_2.1.5 R package):\r\n&gt; Error in py_call_impl(callable, dots$args, dots$keywords) :\r\nValueError: Variable block1_conv1_bn_1/moving_mean/biased already exists, disallowed. Did you mean to set reuse=True in VarScope? Originally defined at:\r\n\r\n&gt; File &quot;D:\\Anaconda3\\lib\\site-packages\\tensorflow\\python\\framework\\ops.py&quot;, line 1269, in init\r\nself._traceback = _extract_stack()\r\nFile &quot;D:\\Anaconda3\\lib\\site-packages\\tensorflow\\python\\framework\\ops.py&quot;, line 2506, in create_op\r\noriginal_op=self._default_original_op, op_def=op_def)\r\nFile &quot;D:\\Anaconda3\\lib\\site-packages\\tensorflow\\python\\framework\\op_def_library.py&quot;, line 767, in apply_op\r\nop_def=op_def)\r\n\r\n&gt; Detailed traceback:\r\nFile &quot;D:\\Anaconda3\\lib\\site-packages\\keras\\models.py&quot;, line 467, in add\r\nlayer(x)\r\nFile &quot;D:\\Anaconda3\\lib\\site-packages\\keras\\engine\\topology.py&quot;, line 617, in call\r\noutput = self.call(inputs, **kwargs)\r\nFile &quot;D:\\Anaconda3\\lib\\site-packages\\keras\\engine\\topology.py&quot;, line 2081, in call\r\noutput_tensors, _, _ = self.run_internal_graph(inputs, masks)\r\nFile &quot;D:\\Anaconda3\\l\r\n\r\n**Further background in case it matters:** I ran into this when trying to replace VGG16 with XCeption in the &quot;Freature extraction with data augementation&quot; subsection of Section 5.3.1 of Chollet and Allaire&#39;s most excellent book (everything in &quot;Fast feature extraction without data augmentation&quot; works just fine with both VGG16 and XCeption).",
            "link": "https://stackoverflow.com/questions/49924675/error-specifying-convolutional-base-from-pre-trained-xception-architecture-with",
            "title": "Error specifying convolutional base from pre-trained XCeption-architecture with keras in R under Windows",
            "body": "<p>Is there something really obvious that I am doing when trying to use the convolutional base from the XCeption architecture pre-trained on ImageNet? Here is my code that produces  the error at the end of the question:</p>\n\n<pre><code>require(keras)\n\nconv_base1 &lt;- application_xception(\nweights = \"imagenet\",\ninclude_top = FALSE,\npooling=FALSE,\ninput_shape = c(300, 300, 3)\n)\n\nmodel51 &lt;- keras_model_sequential() %&gt;%\nconv_base1 %&gt;%\nlayer_flatten() %&gt;%\nlayer_dense(units = 256, activation = \"relu\") %&gt;%\nlayer_dense(units = 1, activation = \"sigmoid\")\n</code></pre>\n\n<p>In contrast, the almost identical code below using application_vgg16 works just fine:</p>\n\n<pre><code>require(keras)\n\nconv_base2 &lt;- application_vgg16(\nweights = \"imagenet\",\ninclude_top = FALSE,\npooling=FALSE,\ninput_shape = c(300, 300, 3)\n)\n\nmodel52 &lt;- keras_model_sequential() %&gt;%\nconv_base2 %&gt;%\nlayer_flatten() %&gt;%\nlayer_dense(units = 2048, activation = \"relu\") %&gt;%\nlayer_dense(units = 1, activation = \"sigmoid\")\n</code></pre>\n\n<p>I get the following errors (using R version 3.4.0 (2017-04-21) on Windows 10 x86_64-w64-mingw32/x64 (64-bit) using the keras_2.1.5 R package):</p>\n\n<blockquote>\n  <p>Error in py_call_impl(callable, dots$args, dots$keywords) :\n  ValueError: Variable block1_conv1_bn_1/moving_mean/biased already exists, disallowed. Did you mean to set reuse=True in VarScope? Originally defined at:</p>\n  \n  <p>File \"D:\\Anaconda3\\lib\\site-packages\\tensorflow\\python\\framework\\ops.py\", line 1269, in init\n  self._traceback = _extract_stack()\n  File \"D:\\Anaconda3\\lib\\site-packages\\tensorflow\\python\\framework\\ops.py\", line 2506, in create_op\n  original_op=self._default_original_op, op_def=op_def)\n  File \"D:\\Anaconda3\\lib\\site-packages\\tensorflow\\python\\framework\\op_def_library.py\", line 767, in apply_op\n  op_def=op_def)</p>\n  \n  <p>Detailed traceback:\n  File \"D:\\Anaconda3\\lib\\site-packages\\keras\\models.py\", line 467, in add\n  layer(x)\n  File \"D:\\Anaconda3\\lib\\site-packages\\keras\\engine\\topology.py\", line 617, in call\n  output = self.call(inputs, **kwargs)\n  File \"D:\\Anaconda3\\lib\\site-packages\\keras\\engine\\topology.py\", line 2081, in call\n  output_tensors, _, _ = self.run_internal_graph(inputs, masks)\n  File \"D:\\Anaconda3\\l</p>\n</blockquote>\n\n<p><strong>Further background in case it matters:</strong> I ran into this when trying to replace VGG16 with XCeption in the \"Freature extraction with data augementation\" subsection of Section 5.3.1 of Chollet and Allaire's most excellent book (everything in \"Fast feature extraction without data augmentation\" works just fine with both VGG16 and XCeption).</p>\n"
        },
        {
            "tags": [
                "laravel",
                "email",
                "message",
                "send"
            ],
            "owner": {
                "reputation": 19,
                "user_id": 9278936,
                "user_type": "registered",
                "accept_rate": 25,
                "profile_image": "https://www.gravatar.com/avatar/1dc8fc6c6d433b6bab4abb0e1c18eb1c?s=128&d=identicon&r=PG&f=1",
                "display_name": "Kristijanas Kiseliovas",
                "link": "https://stackoverflow.com/users/9278936/kristijanas-kiseliovas"
            },
            "is_answered": false,
            "view_count": 17,
            "answer_count": 1,
            "score": 0,
            "last_activity_date": 1524601121,
            "creation_date": 1524599671,
            "question_id": 50009814,
            "body_markdown": "Good evening everyone, I have some issues, with send mail to:\r\nI have a code in controller, and have data taken from database with joins, this $survey variable shows gives me emails of the survey which belongs to team.\r\nBut I need some how to send an email for all emails which I gets from $survey variable. When I put $survey variable inside $message-&gt;to($survey); it shows me **Undefined variable** \r\n\r\nmy code below , how can I use it. When I put in -&gt;to(); normal one email adress it works, but I need to send same email to all team members\r\n\r\n    public function startSurvey(Request $req) {\r\n\r\n        $nameSurvey = $req-&gt;input(&#39;SurveySelectBox&#39;);\r\n        $startDate = $req-&gt;input(&#39;surveyStartDate&#39;);\r\n        $endDate = $req-&gt;input(&#39;surveyEndDate&#39;);\r\n\r\n        $data = array(\r\n            &#39;updated_at&#39; =&gt; Carbon::now(),\r\n            &#39;started_at&#39; =&gt; $startDate,\r\n            &#39;ended_at&#39; =&gt; $endDate\r\n        );\r\n\r\n        DB::table(&#39;survey&#39;)-&gt;where(&#39;surveyId&#39;,&#39;=&#39;,$nameSurvey)-&gt;update($data);\r\n\r\n        $survey = Survey::where(&#39;surveyId&#39; , &#39;=&#39;, $nameSurvey)\r\n            -&gt;join(&#39;team&#39;,&#39;team.teamId&#39;, &#39;=&#39;, &#39;survey.teamId&#39;)\r\n            -&gt;join(&#39;teammembersall&#39;,&#39;teammembersall.TeamId&#39;, &#39;=&#39;, &#39;team.TeamId&#39;)\r\n            -&gt;join(&#39;users&#39;,&#39;users.id&#39;, &#39;=&#39;, &#39;teammembersall.UserId&#39;)\r\n            -&gt;select(&#39;users.email&#39;)\r\n            -&gt;get();\r\n\r\n        Mail::raw(&#39;You have new survey to answer: http://localhost:8000/profile&#39;, function ($message) {\r\n            $message-&gt;from(&#39;kristijanask@gmail.com&#39;, &#39;New Survey released&#39;);\r\n            $message-&gt;to($survey);\r\n        });\r\n\r\n        return redirect(&#39;surveyDrafts&#39;);\r\n    }",
            "link": "https://stackoverflow.com/questions/50009814/laravel-send-mail-to",
            "title": "laravel send mail to",
            "body": "<p>Good evening everyone, I have some issues, with send mail to:\nI have a code in controller, and have data taken from database with joins, this $survey variable shows gives me emails of the survey which belongs to team.\nBut I need some how to send an email for all emails which I gets from $survey variable. When I put $survey variable inside $message->to($survey); it shows me <strong>Undefined variable</strong> </p>\n\n<p>my code below , how can I use it. When I put in ->to(); normal one email adress it works, but I need to send same email to all team members</p>\n\n<pre><code>public function startSurvey(Request $req) {\n\n    $nameSurvey = $req-&gt;input('SurveySelectBox');\n    $startDate = $req-&gt;input('surveyStartDate');\n    $endDate = $req-&gt;input('surveyEndDate');\n\n    $data = array(\n        'updated_at' =&gt; Carbon::now(),\n        'started_at' =&gt; $startDate,\n        'ended_at' =&gt; $endDate\n    );\n\n    DB::table('survey')-&gt;where('surveyId','=',$nameSurvey)-&gt;update($data);\n\n    $survey = Survey::where('surveyId' , '=', $nameSurvey)\n        -&gt;join('team','team.teamId', '=', 'survey.teamId')\n        -&gt;join('teammembersall','teammembersall.TeamId', '=', 'team.TeamId')\n        -&gt;join('users','users.id', '=', 'teammembersall.UserId')\n        -&gt;select('users.email')\n        -&gt;get();\n\n    Mail::raw('You have new survey to answer: http://localhost:8000/profile', function ($message) {\n        $message-&gt;from('kristijanask@gmail.com', 'New Survey released');\n        $message-&gt;to($survey);\n    });\n\n    return redirect('surveyDrafts');\n}\n</code></pre>\n"
        },
        {
            "tags": [
                "regex",
                "python-3.x"
            ],
            "owner": {
                "reputation": 25,
                "user_id": 8126377,
                "user_type": "registered",
                "profile_image": "https://www.gravatar.com/avatar/6879751149645eba087325dcc7399c66?s=128&d=identicon&r=PG&f=1",
                "display_name": "Nonx",
                "link": "https://stackoverflow.com/users/8126377/nonx"
            },
            "is_answered": true,
            "view_count": 44,
            "accepted_answer_id": 50010148,
            "answer_count": 2,
            "score": 1,
            "last_activity_date": 1524601111,
            "creation_date": 1524598462,
            "last_edit_date": 1524600158,
            "question_id": 50009553,
            "body_markdown": "Entry in question:\r\n\r\n&gt;`BOREAS HYD-02 Estimated Snow Water Equivalent (SWE) from Microwave Measurements (BOREAS_H02SWED_256) - https://cmr.earthdata.nasa.gov:443/search/concepts/C179002851-ORNL_DAAC/30.umm-json` \r\n\r\nI need a regex to hit \r\n\r\n&gt;`(BOREAS_H02SWED_256) - https://cmr.earthdata.nasa.gov:443/search/concepts/C179002851-ORNL_DAAC/30.umm-json`\r\n\r\nfrom the entry below such that it yields\r\n\r\n&gt;`BOREAS HYD-02 Estimated Snow Water Equivalent (SWE) from Microwave Measurements`\r\n\r\nMy simple regex of `[(].*` is hitting \r\n\r\n&gt;`(SWE) from Microwave Measurements (BOREAS_H02SWED_256) - https://cmr.earthdata.nasa.gov:443/search/concepts/C179002851-ORNL_DAAC/30.umm-json`\r\n\r\n\r\n",
            "link": "https://stackoverflow.com/questions/50009553/regex-to-hit-parenthesis-but-only-in-a-specific-way",
            "title": "Regex to hit parenthesis, but only in a specific way",
            "body": "<p>Entry in question:</p>\n\n<blockquote>\n  <p><code>BOREAS HYD-02 Estimated Snow Water Equivalent (SWE) from Microwave Measurements (BOREAS_H02SWED_256) - https://cmr.earthdata.nasa.gov:443/search/concepts/C179002851-ORNL_DAAC/30.umm-json</code> </p>\n</blockquote>\n\n<p>I need a regex to hit </p>\n\n<blockquote>\n  <p><code>(BOREAS_H02SWED_256) - https://cmr.earthdata.nasa.gov:443/search/concepts/C179002851-ORNL_DAAC/30.umm-json</code></p>\n</blockquote>\n\n<p>from the entry below such that it yields</p>\n\n<blockquote>\n  <p><code>BOREAS HYD-02 Estimated Snow Water Equivalent (SWE) from Microwave Measurements</code></p>\n</blockquote>\n\n<p>My simple regex of <code>[(].*</code> is hitting </p>\n\n<blockquote>\n  <p><code>(SWE) from Microwave Measurements (BOREAS_H02SWED_256) - https://cmr.earthdata.nasa.gov:443/search/concepts/C179002851-ORNL_DAAC/30.umm-json</code></p>\n</blockquote>\n"
        },
        {
            "tags": [
                "python",
                "ssh",
                "matplotlib"
            ],
            "owner": {
                "reputation": 5178,
                "user_id": 395239,
                "user_type": "registered",
                "accept_rate": 86,
                "profile_image": "https://www.gravatar.com/avatar/9238693c9b69a6f30230ded87fa5af65?s=128&d=identicon&r=PG",
                "display_name": "Mermoz",
                "link": "https://stackoverflow.com/users/395239/mermoz"
            },
            "is_answered": true,
            "view_count": 36854,
            "accepted_answer_id": 3453527,
            "answer_count": 4,
            "score": 32,
            "last_activity_date": 1524601091,
            "creation_date": 1281472499,
            "question_id": 3453188,
            "body_markdown": "I have a python code doing some calculation on a remote machine, named A. I connect on A via `ssh` from a machine named B.\r\nIs there a way to display the figure on machine B?",
            "link": "https://stackoverflow.com/questions/3453188/matplotlib-display-plot-on-a-remote-machine",
            "title": "Matplotlib: display plot on a remote machine",
            "body": "<p>I have a python code doing some calculation on a remote machine, named A. I connect on A via <code>ssh</code> from a machine named B.\nIs there a way to display the figure on machine B?</p>\n"
        },
        {
            "tags": [
                "postgresql",
                "psql",
                "pg-hba.conf"
            ],
            "owner": {
                "reputation": 136,
                "user_id": 2397119,
                "user_type": "registered",
                "accept_rate": 100,
                "profile_image": "https://i.stack.imgur.com/ZAwet.jpg?s=128&g=1",
                "display_name": "Aman Singh",
                "link": "https://stackoverflow.com/users/2397119/aman-singh"
            },
            "is_answered": false,
            "view_count": 17,
            "answer_count": 1,
            "score": 0,
            "last_activity_date": 1524601088,
            "creation_date": 1524549275,
            "question_id": 49994339,
            "body_markdown": "I want to create a backup of the original pg_hba.conf file (may be as pg_hba.conf.bk) and then add an entry into the existing pg_hba.conf file. So far this is what i&#39;ve been trying to do, but every time it says permission denied even if i go via root user or use sudo.\r\n\r\nMy attempt:\r\n\r\n    $ pg_conftool -s 10 main show hba_file\r\n    [OUT] /etc/postgresql/10/main/pg_hba.conf\r\n\r\n    $ sudo cat /etc/postgresql/10/main/pg_hba.conf\r\n        [OUT] local   all             postgres                              peer\r\n              local   all             all                                   md5\r\n              host    all             all             127.0.0.1/32          md5\r\n              host    all             all             ::1/128               md5\r\n\r\nnow when i try adding a line into it, i get the permission denied error\r\n\r\n    $ sudo echo &quot;host all all 0.0.0.0/0 trust&quot; &gt;&gt; /etc/postgresql/10/main/pg_hba.conf\r\n    [OUT] bash: /etc/postgresql/10/main/pg_hba.conf: Permission denied\r\n\r\nThis will be a part of deployment script therefore, I can&#39;t really go and make the entry into the pg_hba.conf manually. So, how can i make an entry into the conf file? ",
            "link": "https://stackoverflow.com/questions/49994339/unable-to-edit-pg-hba-conf-file-in-postgresql",
            "title": "unable to edit pg_hba.conf file in Postgresql",
            "body": "<p>I want to create a backup of the original pg_hba.conf file (may be as pg_hba.conf.bk) and then add an entry into the existing pg_hba.conf file. So far this is what i've been trying to do, but every time it says permission denied even if i go via root user or use sudo.</p>\n\n<p>My attempt:</p>\n\n<pre><code>$ pg_conftool -s 10 main show hba_file\n[OUT] /etc/postgresql/10/main/pg_hba.conf\n\n$ sudo cat /etc/postgresql/10/main/pg_hba.conf\n    [OUT] local   all             postgres                              peer\n          local   all             all                                   md5\n          host    all             all             127.0.0.1/32          md5\n          host    all             all             ::1/128               md5\n</code></pre>\n\n<p>now when i try adding a line into it, i get the permission denied error</p>\n\n<pre><code>$ sudo echo \"host all all 0.0.0.0/0 trust\" &gt;&gt; /etc/postgresql/10/main/pg_hba.conf\n[OUT] bash: /etc/postgresql/10/main/pg_hba.conf: Permission denied\n</code></pre>\n\n<p>This will be a part of deployment script therefore, I can't really go and make the entry into the pg_hba.conf manually. So, how can i make an entry into the conf file? </p>\n"
        },
        {
            "tags": [
                "typescript",
                "promise",
                "jasmine",
                "typemoq"
            ],
            "owner": {
                "reputation": 2810,
                "user_id": 1501327,
                "user_type": "registered",
                "accept_rate": 52,
                "profile_image": "https://www.gravatar.com/avatar/e0926655f7fec6bd7e262d37248aeb79?s=128&d=identicon&r=PG",
                "display_name": "James B",
                "link": "https://stackoverflow.com/users/1501327/james-b"
            },
            "is_answered": true,
            "view_count": 270,
            "answer_count": 1,
            "score": 1,
            "last_activity_date": 1524601084,
            "creation_date": 1495953736,
            "last_edit_date": 1524601084,
            "question_id": 44224528,
            "body_markdown": "I&#39;ve defined `MyService` as follows\r\n\r\n    export interface MyService {\r\n        doStuff(): Promise&lt;any&gt;;\r\n    }\r\n\r\nand `MyClass` that consumes `MyService` as\r\n\r\n    import {MyService} from &quot;./my.service&quot;;\r\n    import {Observable} from &quot;rxjs/Observable&quot;;\r\n    export class MyClass {\r\n    \r\n        constructor(private myService: MyService) {}\r\n    \r\n        useMyService(): Observable&lt;boolean&gt; {\r\n            return Observable.create(obs =&gt; {\r\n                this.myService.doStuff()\r\n                    .then((res: any) =&gt; {\r\n                        console.log(&quot;Promise resolved!&quot;);\r\n                        obs.next(true);\r\n                    })\r\n                    .catch((err: any) =&gt; {\r\n                        console.log(&quot;Promise rejected!&quot;);\r\n                        obs.error(false);\r\n                    })\r\n            });\r\n        };    \r\n    }\r\n\r\nIn addition, I have an interface `MyModel` defined as\r\n\r\n    export interface MyModel {\r\n        someProperty: string;\r\n    }\r\n\r\nNow I want to write a test such that I can mock `MyService` using TypeMoq. So I did the following\r\n\r\n    describe(&#39;MyClass&#39;, () =&gt; {\r\n    \r\n        it(&#39;useMyService returns true when myService returns true&#39;, (done) =&gt; {\r\n            let mockModel = TypeMoq.Mock.ofType&lt;MyModel&gt;();\r\n            mockModel.setup(x =&gt; x.someProperty).returns(() =&gt; &quot;info&quot;);    \r\n   \r\n            let mockMyService = TypeMoq.Mock.ofType&lt;MyService&gt;();\r\n            mockMyService.setup(x =&gt; x.doStuff()).returns(() =&gt; Promise.resolve(mockModel.object));\r\n    \r\n            let myClass = new MyClass(mockMyService.object);\r\n    \r\n            myClass.useMyService().subscribe(\r\n                (result: boolean) =&gt; {\r\n                    expect(result).toBeTruthy();\r\n                    done();\r\n                },\r\n                (error: any) =&gt; {\r\n                    expect(error).toBeFalsy();\r\n                    done();\r\n                });\r\n        });\r\n    });\r\n\r\nHowever, the `Promise.resolve(mockModel.object)` never seems to resolve when supplied with the TypeMoq mock as shown above, i.e., I don&#39;t get &quot;Promise resolved!&quot; (or &quot;Promise rejected!&quot;) printed to the console and the jasmine test times out.\r\n\r\nIf I replace `Promise.resolve(mockModel.object)` with `Promise.resolve({ someProperty: &#39;info&#39;})`, i.e.,\r\n\r\n    let mockMyService = TypeMoq.Mock.ofType&lt;MyService&gt;();\r\n            mockMyService.setup(x =&gt; x.doStuff()).returns(() =&gt; Promise.resolve({ someProperty: &#39;info&#39;}));\r\n\r\n then the test works (I get &quot;Promise resolved!&quot; printed to the console). Why doesn&#39;t `Promise.resolve()` resolve when supplied with a TypeMoq mock?",
            "link": "https://stackoverflow.com/questions/44224528/promise-fails-to-resolve-with-typemoq-mock",
            "title": "Promise Fails to Resolve with TypeMoq Mock",
            "body": "<p>I've defined <code>MyService</code> as follows</p>\n\n<pre><code>export interface MyService {\n    doStuff(): Promise&lt;any&gt;;\n}\n</code></pre>\n\n<p>and <code>MyClass</code> that consumes <code>MyService</code> as</p>\n\n<pre><code>import {MyService} from \"./my.service\";\nimport {Observable} from \"rxjs/Observable\";\nexport class MyClass {\n\n    constructor(private myService: MyService) {}\n\n    useMyService(): Observable&lt;boolean&gt; {\n        return Observable.create(obs =&gt; {\n            this.myService.doStuff()\n                .then((res: any) =&gt; {\n                    console.log(\"Promise resolved!\");\n                    obs.next(true);\n                })\n                .catch((err: any) =&gt; {\n                    console.log(\"Promise rejected!\");\n                    obs.error(false);\n                })\n        });\n    };    \n}\n</code></pre>\n\n<p>In addition, I have an interface <code>MyModel</code> defined as</p>\n\n<pre><code>export interface MyModel {\n    someProperty: string;\n}\n</code></pre>\n\n<p>Now I want to write a test such that I can mock <code>MyService</code> using TypeMoq. So I did the following</p>\n\n<pre><code>describe('MyClass', () =&gt; {\n\n    it('useMyService returns true when myService returns true', (done) =&gt; {\n        let mockModel = TypeMoq.Mock.ofType&lt;MyModel&gt;();\n        mockModel.setup(x =&gt; x.someProperty).returns(() =&gt; \"info\");    \n\n        let mockMyService = TypeMoq.Mock.ofType&lt;MyService&gt;();\n        mockMyService.setup(x =&gt; x.doStuff()).returns(() =&gt; Promise.resolve(mockModel.object));\n\n        let myClass = new MyClass(mockMyService.object);\n\n        myClass.useMyService().subscribe(\n            (result: boolean) =&gt; {\n                expect(result).toBeTruthy();\n                done();\n            },\n            (error: any) =&gt; {\n                expect(error).toBeFalsy();\n                done();\n            });\n    });\n});\n</code></pre>\n\n<p>However, the <code>Promise.resolve(mockModel.object)</code> never seems to resolve when supplied with the TypeMoq mock as shown above, i.e., I don't get \"Promise resolved!\" (or \"Promise rejected!\") printed to the console and the jasmine test times out.</p>\n\n<p>If I replace <code>Promise.resolve(mockModel.object)</code> with <code>Promise.resolve({ someProperty: 'info'})</code>, i.e.,</p>\n\n<pre><code>let mockMyService = TypeMoq.Mock.ofType&lt;MyService&gt;();\n        mockMyService.setup(x =&gt; x.doStuff()).returns(() =&gt; Promise.resolve({ someProperty: 'info'}));\n</code></pre>\n\n<p>then the test works (I get \"Promise resolved!\" printed to the console). Why doesn't <code>Promise.resolve()</code> resolve when supplied with a TypeMoq mock?</p>\n"
        },
        {
            "tags": [
                "publish-subscribe"
            ],
            "owner": {
                "reputation": 224,
                "user_id": 5072383,
                "user_type": "registered",
                "accept_rate": 47,
                "profile_image": "https://www.gravatar.com/avatar/9039eeba3db287425affe4fc2f7ee7f8?s=128&d=identicon&r=PG&f=1",
                "display_name": "joethemow",
                "link": "https://stackoverflow.com/users/5072383/joethemow"
            },
            "is_answered": false,
            "view_count": 4,
            "answer_count": 0,
            "score": 0,
            "last_activity_date": 1524601083,
            "creation_date": 1524601083,
            "question_id": 50010141,
            "body_markdown": "I have built an internal api to communicate with my own db which is pretty simple. However, I am beginning to use 3rd party apis such as Google Maps. I am doing a lot of research and coming across using a pub/sub system such as Apache Kafka or RabbitMQ. I understand the basics of consumer, producers, broker, client etc. I am not asking for how pub/sub actually works, I have read the documentation. I am seeking advice on the actual implementation. 1) Do I run Kafka or whichever pub/sub system I choose on its own separate server or on the same server as my internal API. 2) If I need to receive say data about a particular route from Google API and display it in my mobile application, which components would be my producer/consumer? ",
            "link": "https://stackoverflow.com/questions/50010141/using-pub-sub-system-for-communicating-with-3rd-party-apis",
            "title": "Using pub/sub system for communicating with 3rd party apis",
            "body": "<p>I have built an internal api to communicate with my own db which is pretty simple. However, I am beginning to use 3rd party apis such as Google Maps. I am doing a lot of research and coming across using a pub/sub system such as Apache Kafka or RabbitMQ. I understand the basics of consumer, producers, broker, client etc. I am not asking for how pub/sub actually works, I have read the documentation. I am seeking advice on the actual implementation. 1) Do I run Kafka or whichever pub/sub system I choose on its own separate server or on the same server as my internal API. 2) If I need to receive say data about a particular route from Google API and display it in my mobile application, which components would be my producer/consumer? </p>\n"
        },
        {
            "tags": [
                "python",
                "macos",
                "lightgbm"
            ],
            "owner": {
                "reputation": 868,
                "user_id": 1558119,
                "user_type": "registered",
                "accept_rate": 59,
                "profile_image": "https://i.stack.imgur.com/R5vbU.jpg?s=128&g=1",
                "display_name": "LampShade",
                "link": "https://stackoverflow.com/users/1558119/lampshade"
            },
            "is_answered": true,
            "view_count": 1423,
            "accepted_answer_id": 44967912,
            "answer_count": 4,
            "score": 3,
            "last_activity_date": 1524601068,
            "creation_date": 1499298664,
            "question_id": 44937698,
            "body_markdown": "If I simply do:\r\n\r\n    import lightgbm as lgb\r\n\r\nI&#39;m getting\r\n\r\n    python script.py \r\n    Traceback (most recent call last):\r\n    File &quot;script.py&quot;, line 4, in &lt;module&gt;\r\n    import lightgbm as lgb\r\n    File &quot;/usr/local/lib/python2.7/site-packages/lightgbm/__init__.py&quot;, line 8, in &lt;module&gt;\r\n    from .basic import Booster, Dataset\r\n    File &quot;/usr/local/lib/python2.7/site-packages/lightgbm/basic.py&quot;, line 31, in &lt;module&gt;\r\n    _LIB = _load_lib()\r\n    File &quot;/usr/local/lib/python2.7/site-packages/lightgbm/basic.py&quot;, line 26, in _load_lib\r\n    lib = ctypes.cdll.LoadLibrary(lib_path[0])\r\n    File &quot;/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ctypes/__init__.py&quot;, line 440, in LoadLibrary\r\n    return self._dlltype(name)\r\n    File &quot;/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ctypes/__init__.py&quot;, line 362, in __init__\r\n    self._handle = _dlopen(self._name, mode)\r\n    OSError: dlopen(/usr/local/lib/python2.7/site-packages/lightgbm/lib_lightgbm.so, 6): Library not loaded: /usr/local/opt/gcc/lib/gcc/7/libgomp.1.dylib\r\n    Referenced from: /usr/local/lib/python2.7/site-packages/lightgbm/lib_lightgbm.so\r\n    Reason: image not found\r\n\r\nI seem to have everything installed correct:\r\n\r\n    python -m pip install lightgbm\r\n    Requirement already satisfied: lightgbm in /usr/local/lib/python2.7/site-packages\r\n    Requirement already satisfied: wheel in /usr/local/lib/python2.7/site-packages (from lightgbm)\r\n    Requirement already satisfied: scikit-learn in /usr/local/lib/python2.7/site-packages (from lightgbm)\r\n    Requirement already satisfied: scipy in /usr/local/lib/python2.7/site-packages (from lightgbm)\r\n    Requirement already satisfied: numpy in /usr/local/lib/python2.7/site-packages (from lightgbm)\r\n\r\nI do have a 6 folder in my GCC folder.  Should I need to install another version of GCC for this to work?  \r\n\r\n[![enter image description here][1]][1]\r\n\r\n\r\n  [1]: https://i.stack.imgur.com/Wl9Ld.png",
            "link": "https://stackoverflow.com/questions/44937698/lightgbm-oserror-library-not-loaded",
            "title": "Lightgbm OSError, Library not loaded",
            "body": "<p>If I simply do:</p>\n\n<pre><code>import lightgbm as lgb\n</code></pre>\n\n<p>I'm getting</p>\n\n<pre><code>python script.py \nTraceback (most recent call last):\nFile \"script.py\", line 4, in &lt;module&gt;\nimport lightgbm as lgb\nFile \"/usr/local/lib/python2.7/site-packages/lightgbm/__init__.py\", line 8, in &lt;module&gt;\nfrom .basic import Booster, Dataset\nFile \"/usr/local/lib/python2.7/site-packages/lightgbm/basic.py\", line 31, in &lt;module&gt;\n_LIB = _load_lib()\nFile \"/usr/local/lib/python2.7/site-packages/lightgbm/basic.py\", line 26, in _load_lib\nlib = ctypes.cdll.LoadLibrary(lib_path[0])\nFile \"/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ctypes/__init__.py\", line 440, in LoadLibrary\nreturn self._dlltype(name)\nFile \"/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ctypes/__init__.py\", line 362, in __init__\nself._handle = _dlopen(self._name, mode)\nOSError: dlopen(/usr/local/lib/python2.7/site-packages/lightgbm/lib_lightgbm.so, 6): Library not loaded: /usr/local/opt/gcc/lib/gcc/7/libgomp.1.dylib\nReferenced from: /usr/local/lib/python2.7/site-packages/lightgbm/lib_lightgbm.so\nReason: image not found\n</code></pre>\n\n<p>I seem to have everything installed correct:</p>\n\n<pre><code>python -m pip install lightgbm\nRequirement already satisfied: lightgbm in /usr/local/lib/python2.7/site-packages\nRequirement already satisfied: wheel in /usr/local/lib/python2.7/site-packages (from lightgbm)\nRequirement already satisfied: scikit-learn in /usr/local/lib/python2.7/site-packages (from lightgbm)\nRequirement already satisfied: scipy in /usr/local/lib/python2.7/site-packages (from lightgbm)\nRequirement already satisfied: numpy in /usr/local/lib/python2.7/site-packages (from lightgbm)\n</code></pre>\n\n<p>I do have a 6 folder in my GCC folder.  Should I need to install another version of GCC for this to work?  </p>\n\n<p><a href=\"https://i.stack.imgur.com/Wl9Ld.png\" rel=\"nofollow noreferrer\"><img src=\"https://i.stack.imgur.com/Wl9Ld.png\" alt=\"enter image description here\"></a></p>\n"
        },
        {
            "tags": [
                "react-native",
                "components",
                "lifecycle",
                "native-base"
            ],
            "owner": {
                "reputation": 1862,
                "user_id": 1460189,
                "user_type": "registered",
                "accept_rate": 72,
                "profile_image": "https://i.stack.imgur.com/WkdJT.jpg?s=128&g=1",
                "display_name": "Isaac Lem",
                "link": "https://stackoverflow.com/users/1460189/isaac-lem"
            },
            "is_answered": true,
            "view_count": 123,
            "answer_count": 1,
            "score": 1,
            "last_activity_date": 1524601064,
            "creation_date": 1523977882,
            "question_id": 49881731,
            "body_markdown": "MainComponent:\r\n\r\n    &lt;Tabs \r\n      initialPage={this.props.day}\r\n      tabBarUnderlineStyle={{ backgroundColor: &#39;#5AF158&#39; }} \r\n      renderTabBar={() =&gt; &lt;ScrollableTab /&gt;}&gt;\r\n      {this.renderTabHeader()}\r\n    &lt;/Tabs&gt;\r\n\r\n    renderTabHeader() {\r\n      return (\r\n        this.props.dateArray.map((date, i) =&gt; \r\n          &lt;Tab \r\n            key={i}\r\n            heading={date.format(&#39;DD/MM&#39;)} \r\n            tabStyle={styles.tabStyling} \r\n            activeTabStyle={styles.activeTabStyle} \r\n            textStyle={styles.tabTextStyle} \r\n            activeTextStyle={styles.activeTabTextStyle} \r\n          &gt;\r\n            &lt;View style={{ backgroundColor: &#39;#EEEEEE&#39;, flex: 1 }}&gt;\r\n              &lt;Content contentDate={date.format(&#39;YYYY-MM-DD&#39;)} /&gt;\r\n            &lt;/View&gt;\r\n          &lt;/Tab&gt;\r\n        )\r\n      );\r\n    }\r\n\r\nContent Component:\r\n\r\n    class Content extends Component {\r\n      componentWillMount() {\r\n        console.log(&#39;Component Will Mount() ?&#39;);\r\n        this.props.loadTransactionByDate({ date: this.props.contentDate });\r\n      }\r\n\r\n    render() {\r\n      return (\r\n        &lt;View&gt;&lt;Text&gt;{this.props.contentDate}&lt;/Text&gt;&lt;/View&gt;\r\n      );\r\n      }\r\n\r\n\r\nBasically, in MainComponent there is a collection of tabs. I&#39;ve noticed something rather weird which `Content` will be mounted on the first time their tab being click or active? \r\n\r\nMeaning for the first time, we can click on Tab index 2 and seeing the console log in `componentWillMount`, then we switch to another tab and if coming back to Tab index 2 again, `componentWillMount` will not be triggered anymore?  ",
            "link": "https://stackoverflow.com/questions/49881731/componentwillmount-only-trigger-for-first-time",
            "title": "ComponentWillMount only trigger for first time?",
            "body": "<p>MainComponent:</p>\n\n<pre><code>&lt;Tabs \n  initialPage={this.props.day}\n  tabBarUnderlineStyle={{ backgroundColor: '#5AF158' }} \n  renderTabBar={() =&gt; &lt;ScrollableTab /&gt;}&gt;\n  {this.renderTabHeader()}\n&lt;/Tabs&gt;\n\nrenderTabHeader() {\n  return (\n    this.props.dateArray.map((date, i) =&gt; \n      &lt;Tab \n        key={i}\n        heading={date.format('DD/MM')} \n        tabStyle={styles.tabStyling} \n        activeTabStyle={styles.activeTabStyle} \n        textStyle={styles.tabTextStyle} \n        activeTextStyle={styles.activeTabTextStyle} \n      &gt;\n        &lt;View style={{ backgroundColor: '#EEEEEE', flex: 1 }}&gt;\n          &lt;Content contentDate={date.format('YYYY-MM-DD')} /&gt;\n        &lt;/View&gt;\n      &lt;/Tab&gt;\n    )\n  );\n}\n</code></pre>\n\n<p>Content Component:</p>\n\n<pre><code>class Content extends Component {\n  componentWillMount() {\n    console.log('Component Will Mount() ?');\n    this.props.loadTransactionByDate({ date: this.props.contentDate });\n  }\n\nrender() {\n  return (\n    &lt;View&gt;&lt;Text&gt;{this.props.contentDate}&lt;/Text&gt;&lt;/View&gt;\n  );\n  }\n</code></pre>\n\n<p>Basically, in MainComponent there is a collection of tabs. I've noticed something rather weird which <code>Content</code> will be mounted on the first time their tab being click or active? </p>\n\n<p>Meaning for the first time, we can click on Tab index 2 and seeing the console log in <code>componentWillMount</code>, then we switch to another tab and if coming back to Tab index 2 again, <code>componentWillMount</code> will not be triggered anymore?  </p>\n"
        },
        {
            "tags": [
                "javascript",
                "node.js",
                "screen-capture"
            ],
            "owner": {
                "reputation": 11238,
                "user_id": 117658,
                "user_type": "registered",
                "accept_rate": 87,
                "profile_image": "https://i.stack.imgur.com/ps1LY.jpg?s=128&g=1",
                "display_name": "Jack Marchetti",
                "link": "https://stackoverflow.com/users/117658/jack-marchetti"
            },
            "is_answered": false,
            "view_count": 12,
            "answer_count": 0,
            "score": 0,
            "last_activity_date": 1524601057,
            "creation_date": 1524601057,
            "question_id": 50010138,
            "body_markdown": "I have a pretty simple node.js program using [PageRes][1].  Given a URL, it takes a screenshot.\r\n\r\nHowever, I&#39;m running into issues where it works on some websites but not on others. These are sites that I have access to so if it&#39;s a configuration issue I&#39;ll have the ability to solve it.  I thought perhaps a `robots.txt` was blocking, but `robots.txt` is allowing all traffic. \r\n\r\nHere is the code, which is pretty boilerplate for pageres:\r\n    \r\n    \r\n    const pageres = new Pageres({ \r\n        username: &#39;username&#39;, \r\n        password: &#39;password&#39;,  \r\n        delay: 5, \r\n        filename: &#39;&lt;%= url %&gt; - &lt;%= date %&gt;&#39;\r\n    })\r\n        .src(&#39;http://stage.website.com/en-my&#39;, [&#39;1920x1080&#39;]\r\n    \t.dest(__dirname)\r\n        .run()\r\n    \t.then(() =&gt; console.log(&#39;done&#39;));\r\n\r\n\r\nI receive no error message.  The program runs, then just stops.\r\n\r\nI assume this is a server configuration issue since I can get this to work on some sites and not others but I&#39;m not sure what sort of configuration to look for.\r\n\r\n\r\n  [1]: https://github.com/sindresorhus/pageres",
            "link": "https://stackoverflow.com/questions/50010138/node-js-pageres-doesnt-work-on-certain-urls",
            "title": "Node.js PageRes doesn&#39;t work on certain URLs",
            "body": "<p>I have a pretty simple node.js program using <a href=\"https://github.com/sindresorhus/pageres\" rel=\"nofollow noreferrer\">PageRes</a>.  Given a URL, it takes a screenshot.</p>\n\n<p>However, I'm running into issues where it works on some websites but not on others. These are sites that I have access to so if it's a configuration issue I'll have the ability to solve it.  I thought perhaps a <code>robots.txt</code> was blocking, but <code>robots.txt</code> is allowing all traffic. </p>\n\n<p>Here is the code, which is pretty boilerplate for pageres:</p>\n\n<pre><code>const pageres = new Pageres({ \n    username: 'username', \n    password: 'password',  \n    delay: 5, \n    filename: '&lt;%= url %&gt; - &lt;%= date %&gt;'\n})\n    .src('http://stage.website.com/en-my', ['1920x1080']\n    .dest(__dirname)\n    .run()\n    .then(() =&gt; console.log('done'));\n</code></pre>\n\n<p>I receive no error message.  The program runs, then just stops.</p>\n\n<p>I assume this is a server configuration issue since I can get this to work on some sites and not others but I'm not sure what sort of configuration to look for.</p>\n"
        },
        {
            "tags": [
                "javascript",
                "jquery",
                "css"
            ],
            "owner": {
                "reputation": 1,
                "user_id": 9544763,
                "user_type": "registered",
                "profile_image": "https://lh3.googleusercontent.com/-XdUIqdMkCWA/AAAAAAAAAAI/AAAAAAAAAAA/4252rscbv5M/photo.jpg?sz=128",
                "display_name": "Petra Žagar",
                "link": "https://stackoverflow.com/users/9544763/petra-%c5%bdagar"
            },
            "is_answered": false,
            "view_count": 38,
            "answer_count": 2,
            "score": 0,
            "last_activity_date": 1524601052,
            "creation_date": 1524598832,
            "question_id": 50009643,
            "body_markdown": "I am trying to change number(text) &quot;1&quot; in my form (gravity form) with star icon:\r\n\r\nhttps://fontawesome.com/icons/star?style=regular\r\n\r\nIt must go sth like that i guess:\r\n\r\n    &lt;script&gt;\r\n    $(&quot;#label_13_5_0&quot;).text(function () {\r\n        return $(this).attr(&quot;1&quot;).text().replace(&quot;1&quot;, &quot;star&quot;);\r\n    });\r\n    &lt;/script&gt;\r\n\r\nThis does not work\r\n\r\nMy website (u can see number in my form that heas to be replaced with stars):\r\n\r\nhttp://online.pravneresitve.si/anketa-o-zdavoljstvu/\r\n\r\n",
            "link": "https://stackoverflow.com/questions/50009643/how-to-change-text-with-icon-with-css-or-js",
            "title": "How to change text with icon with css or js",
            "body": "<p>I am trying to change number(text) \"1\" in my form (gravity form) with star icon:</p>\n\n<p><a href=\"https://fontawesome.com/icons/star?style=regular\" rel=\"nofollow noreferrer\">https://fontawesome.com/icons/star?style=regular</a></p>\n\n<p>It must go sth like that i guess:</p>\n\n<pre><code>&lt;script&gt;\n$(\"#label_13_5_0\").text(function () {\n    return $(this).attr(\"1\").text().replace(\"1\", \"star\");\n});\n&lt;/script&gt;\n</code></pre>\n\n<p>This does not work</p>\n\n<p>My website (u can see number in my form that heas to be replaced with stars):</p>\n\n<p><a href=\"http://online.pravneresitve.si/anketa-o-zdavoljstvu/\" rel=\"nofollow noreferrer\">http://online.pravneresitve.si/anketa-o-zdavoljstvu/</a></p>\n"
        },
        {
            "tags": [
                "sonarqube"
            ],
            "owner": {
                "reputation": 167,
                "user_id": 480281,
                "user_type": "registered",
                "accept_rate": 80,
                "profile_image": "https://i.stack.imgur.com/Tr7GM.jpg?s=128&g=1",
                "display_name": "jgxvx",
                "link": "https://stackoverflow.com/users/480281/jgxvx"
            },
            "is_answered": true,
            "view_count": 24,
            "accepted_answer_id": 50010136,
            "answer_count": 1,
            "score": 1,
            "last_activity_date": 1524601049,
            "creation_date": 1524481294,
            "question_id": 49979507,
            "body_markdown": "**Configuration Details**\r\n\r\nWe have a SonarQube 6.7.2 (build 37468) on-premise installation running.\r\n\r\nThe instance is accessible from our office IP **without** HTTP Basic Auth, as well as from everywhere else **with** HTTP Basic Auth.\r\n\r\nThe &quot;Force user authentication&quot; option is off.\r\n\r\nAll projects are set to private - in case someone gets past the HTTP Basic Auth.\r\n\r\nMy user belongs to the sonar-administrators groups and has &quot;Browse&quot; and &quot;See Source Code&quot; permissions on all projects.\r\n\r\nUsing the web interface in the browser, I am able to see all projects including analysis results etc., as expected.\r\n\r\n**Problem**\r\n\r\nHowever, using the Web API, I receive &quot;Insufficient Privileges&quot; errors on several API calls.\r\n\r\nMy user has a valid token that I pass to cURL [as described in the documentation][1]. I even created a new token, to be sure I&#39;m not using an invalid one.\r\n\r\n**Example**\r\n\r\n    $ curl -X GET -u my_user_token: https://sonar.example.org/api/measures/search_history?component=the_project&amp;metrics=lines_to_cover%2Cuncovered_lines%2Ccoverage&amp;ps=1000\r\n    {&quot;errors&quot;:[{&quot;msg&quot;:&quot;Insufficient privileges&quot;}]}\r\n\r\n**Question**\r\n\r\nIs it not possible to retrieve measures information or project information via the API for projects that are set to private?\r\n\r\nThe above call works fine if the project is to public. (But then again, if the project is set to public, that call works fine even without authentication.)\r\n\r\nWe do have the same issue when using the SonarLint plugin for PHPStorm. The plugin works fine as long as the projects are public, but server sync stops working as soon as projects are set to private.\r\n\r\nI&#39;m thinking maybe it would be best to deny all requests to SonarQube except from our whitelisted office IP and have everyone connect via VPN if they want to access the instance from their home office. That would allow us to make all projects public and not have any of these issues. Is that the recommended way to run an on-premise installation of SonarQube?\r\n\r\n\r\n  [1]: https://docs.sonarqube.org/display/DEV/Web+API",
            "link": "https://stackoverflow.com/questions/49979507/web-api-insufficient-privileges-on-private-projects",
            "title": "Web API: Insufficient Privileges on Private Projects",
            "body": "<p><strong>Configuration Details</strong></p>\n\n<p>We have a SonarQube 6.7.2 (build 37468) on-premise installation running.</p>\n\n<p>The instance is accessible from our office IP <strong>without</strong> HTTP Basic Auth, as well as from everywhere else <strong>with</strong> HTTP Basic Auth.</p>\n\n<p>The \"Force user authentication\" option is off.</p>\n\n<p>All projects are set to private - in case someone gets past the HTTP Basic Auth.</p>\n\n<p>My user belongs to the sonar-administrators groups and has \"Browse\" and \"See Source Code\" permissions on all projects.</p>\n\n<p>Using the web interface in the browser, I am able to see all projects including analysis results etc., as expected.</p>\n\n<p><strong>Problem</strong></p>\n\n<p>However, using the Web API, I receive \"Insufficient Privileges\" errors on several API calls.</p>\n\n<p>My user has a valid token that I pass to cURL <a href=\"https://docs.sonarqube.org/display/DEV/Web+API\" rel=\"nofollow noreferrer\">as described in the documentation</a>. I even created a new token, to be sure I'm not using an invalid one.</p>\n\n<p><strong>Example</strong></p>\n\n<pre><code>$ curl -X GET -u my_user_token: https://sonar.example.org/api/measures/search_history?component=the_project&amp;metrics=lines_to_cover%2Cuncovered_lines%2Ccoverage&amp;ps=1000\n{\"errors\":[{\"msg\":\"Insufficient privileges\"}]}\n</code></pre>\n\n<p><strong>Question</strong></p>\n\n<p>Is it not possible to retrieve measures information or project information via the API for projects that are set to private?</p>\n\n<p>The above call works fine if the project is to public. (But then again, if the project is set to public, that call works fine even without authentication.)</p>\n\n<p>We do have the same issue when using the SonarLint plugin for PHPStorm. The plugin works fine as long as the projects are public, but server sync stops working as soon as projects are set to private.</p>\n\n<p>I'm thinking maybe it would be best to deny all requests to SonarQube except from our whitelisted office IP and have everyone connect via VPN if they want to access the instance from their home office. That would allow us to make all projects public and not have any of these issues. Is that the recommended way to run an on-premise installation of SonarQube?</p>\n"
        },
        {
            "tags": [
                "apache",
                "ssl",
                "ldap",
                "samba"
            ],
            "owner": {
                "reputation": 10,
                "user_id": 5106891,
                "user_type": "registered",
                "profile_image": "https://www.gravatar.com/avatar/b1183abc247c7f2e9cbf8120d2297ac0?s=128&d=identicon&r=PG&f=1",
                "display_name": "sivacrom",
                "link": "https://stackoverflow.com/users/5106891/sivacrom"
            },
            "is_answered": true,
            "view_count": 18,
            "accepted_answer_id": 50007385,
            "answer_count": 1,
            "score": 0,
            "last_activity_date": 1524601048,
            "creation_date": 1524259695,
            "question_id": 49949965,
            "body_markdown": "I have a webpage that&#39;s behind a restricted realm on a web server. To get by, people have to authenticate with their Samba Active Directory account. To accomplish this, I have always used the following configuration settings in my httpd.conf file for this site:\r\n\r\n    &lt;Directory &quot;${TOP_DIR}/public_html&gt;\r\n      AuthName &quot;My Company&#39;s Totally Protected Schtuff&quot;\r\n      AuthType Basic\r\n      AuthBasicProvider ldap\r\n      AuthLDAPURL &quot;ldap://dc01.example.com:389/dc=samdom,dc=example,dc=com?samaccountname&quot;\r\n      AuthLDAPBindDN &quot;CN=privileged user,CN=Users,DC=samdom,DC=example,DC=com&quot;\r\n      AuthLDAPBindPassword &quot;totallySw33tpa$$w0rd&quot;\r\n      AuthUserFile /dev/null\r\n      Require valid-user\r\n    &lt;/Directory&gt;\r\n\r\nWell, my samba DCs all have SSL certificates now, granted to them by a CA. So I have changed my configuration like so:\r\n\r\n    &lt;Directory &quot;${TOP_DIR}/public_html&gt;\r\n      AuthName &quot;My Company&#39;s Totally Protected Schtuff&quot;\r\n      AuthType Basic\r\n      AuthBasicProvider ldap\r\n      AuthLDAPURL &quot;ldaps://dc01.example.com:636/dc=samdom,dc=example,dc=com?samaccountname&quot;\r\n      AuthLDAPBindDN &quot;CN=privileged user,CN=Users,DC=samdom,DC=example,DC=com&quot;\r\n      AuthLDAPBindPassword &quot;totallySw33tpa$$w0rd&quot;\r\n      AuthUserFile /dev/null\r\n      Require valid-user\r\n    &lt;/Directory&gt;\r\n\r\nMost servers on my network are handling LDAPS well, but my Apache2 server is not liking it. Reloading the services goes just fine; no errors. I can even go to the site and I am presented with a username and password prompt, which appears to work if I enter credentials correctly. But, instead of the beautiful web page I am expecting to see, I see this message:\r\n\r\n&gt; Internal Server Error\r\n&gt; \r\n&gt; The server encountered an internal error or misconfiguration and was unable to complete your request.\r\n&gt; \r\n&gt; Please contact the server administrator at webmaster@example.com to inform them of the time this error occurred, and the actions you performed just before this error.\r\n&gt; \r\n&gt; More information about this error may be available in the server error log.\r\n&gt; \r\n&gt; Apache/2.4.18 (Ubuntu) Server at restricted.example.com Port 443\r\n\r\nA visit to my error logs tells me nothing. Can anyone with masterful skills on LDAPS in Apache2 provide any insight? I&#39;ll settle for not-masterful-skills, as long as it works.",
            "link": "https://stackoverflow.com/questions/49949965/ldaps-authentication-in-an-httpd-conf-file-fails",
            "title": "LDAPS Authentication in an httpd.conf file fails",
            "body": "<p>I have a webpage that's behind a restricted realm on a web server. To get by, people have to authenticate with their Samba Active Directory account. To accomplish this, I have always used the following configuration settings in my httpd.conf file for this site:</p>\n\n<pre><code>&lt;Directory \"${TOP_DIR}/public_html&gt;\n  AuthName \"My Company's Totally Protected Schtuff\"\n  AuthType Basic\n  AuthBasicProvider ldap\n  AuthLDAPURL \"ldap://dc01.example.com:389/dc=samdom,dc=example,dc=com?samaccountname\"\n  AuthLDAPBindDN \"CN=privileged user,CN=Users,DC=samdom,DC=example,DC=com\"\n  AuthLDAPBindPassword \"totallySw33tpa$$w0rd\"\n  AuthUserFile /dev/null\n  Require valid-user\n&lt;/Directory&gt;\n</code></pre>\n\n<p>Well, my samba DCs all have SSL certificates now, granted to them by a CA. So I have changed my configuration like so:</p>\n\n<pre><code>&lt;Directory \"${TOP_DIR}/public_html&gt;\n  AuthName \"My Company's Totally Protected Schtuff\"\n  AuthType Basic\n  AuthBasicProvider ldap\n  AuthLDAPURL \"ldaps://dc01.example.com:636/dc=samdom,dc=example,dc=com?samaccountname\"\n  AuthLDAPBindDN \"CN=privileged user,CN=Users,DC=samdom,DC=example,DC=com\"\n  AuthLDAPBindPassword \"totallySw33tpa$$w0rd\"\n  AuthUserFile /dev/null\n  Require valid-user\n&lt;/Directory&gt;\n</code></pre>\n\n<p>Most servers on my network are handling LDAPS well, but my Apache2 server is not liking it. Reloading the services goes just fine; no errors. I can even go to the site and I am presented with a username and password prompt, which appears to work if I enter credentials correctly. But, instead of the beautiful web page I am expecting to see, I see this message:</p>\n\n<blockquote>\n  <p>Internal Server Error</p>\n  \n  <p>The server encountered an internal error or misconfiguration and was unable to complete your request.</p>\n  \n  <p>Please contact the server administrator at webmaster@example.com to inform them of the time this error occurred, and the actions you performed just before this error.</p>\n  \n  <p>More information about this error may be available in the server error log.</p>\n  \n  <p>Apache/2.4.18 (Ubuntu) Server at restricted.example.com Port 443</p>\n</blockquote>\n\n<p>A visit to my error logs tells me nothing. Can anyone with masterful skills on LDAPS in Apache2 provide any insight? I'll settle for not-masterful-skills, as long as it works.</p>\n"
        },
        {
            "tags": [
                "apache-spark",
                "hive",
                "distcp",
                "s3distcp",
                "awss3"
            ],
            "owner": {
                "reputation": 485,
                "user_id": 5289111,
                "user_type": "registered",
                "accept_rate": 33,
                "profile_image": "https://i.stack.imgur.com/Pvn1P.jpg?s=128&g=1",
                "display_name": "nagendra",
                "link": "https://stackoverflow.com/users/5289111/nagendra"
            },
            "is_answered": false,
            "view_count": 24,
            "answer_count": 1,
            "score": -1,
            "last_activity_date": 1524601038,
            "creation_date": 1523850301,
            "question_id": 49849329,
            "body_markdown": "I have a requirement to move text files in hdfs to aws s3. The files in HDFS are text files and non-partitioned.The output of the S3 files after migration should be in orc and partitioned on specific column. Finally a hive table is created on top of this data.\r\n\r\nOne way to achieve this is using spark. But I would like to know, is this possible using Distcp to copy files as ORC.\r\n\r\nWould like to know any other best option is available to accomplish the above task.\r\n\r\nThanks in Advance.",
            "link": "https://stackoverflow.com/questions/49849329/how-to-move-hdfs-files-as-orc-files-in-s3-using-distcp",
            "title": "how to move hdfs files as ORC files in S3 using distcp?",
            "body": "<p>I have a requirement to move text files in hdfs to aws s3. The files in HDFS are text files and non-partitioned.The output of the S3 files after migration should be in orc and partitioned on specific column. Finally a hive table is created on top of this data.</p>\n\n<p>One way to achieve this is using spark. But I would like to know, is this possible using Distcp to copy files as ORC.</p>\n\n<p>Would like to know any other best option is available to accomplish the above task.</p>\n\n<p>Thanks in Advance.</p>\n"
        },
        {
            "tags": [
                "image",
                "rotation",
                "keras"
            ],
            "owner": {
                "reputation": 1,
                "user_id": 9549155,
                "user_type": "registered",
                "profile_image": "https://www.gravatar.com/avatar/1dcfdcb4294c6238c1ebdee94a95f760?s=128&d=identicon&r=PG&f=1",
                "display_name": "Didier",
                "link": "https://stackoverflow.com/users/9549155/didier"
            },
            "is_answered": false,
            "view_count": 12,
            "answer_count": 1,
            "score": 0,
            "last_activity_date": 1524601038,
            "creation_date": 1524596412,
            "last_edit_date": 1524596721,
            "question_id": 50009063,
            "body_markdown": "Hi I just want my databasis of MNIST randomly rotated:\r\n\r\nI have my X which is a numpy array (5000, 1, 28, 28)\r\nI want the X_rotated in the same order same dimension.\r\n\r\nI have made this:\r\n\r\n\r\ndatagen = ImageDataGenerator(rotation_range=360)\r\n\r\ndatagen.fit(X)\r\n\r\nNow how I get my X_rotated ? \r\n\r\nThey only explain how to make tricky stuff with epoch and batch I just want to get back my array where each image has randomly rotated nothing more, nothing tricky.\r\nI don&#39;t understand why on tutorials they only explain how to make the tricky stuff but not the basics...\r\n\r\nhttps://keras.io/preprocessing/image/",
            "link": "https://stackoverflow.com/questions/50009063/how-to-get-my-x-rotated-with-keras-imagedatagenerator",
            "title": "How to get my X_rotated with Keras ImageDataGenerator",
            "body": "<p>Hi I just want my databasis of MNIST randomly rotated:</p>\n\n<p>I have my X which is a numpy array (5000, 1, 28, 28)\nI want the X_rotated in the same order same dimension.</p>\n\n<p>I have made this:</p>\n\n<p>datagen = ImageDataGenerator(rotation_range=360)</p>\n\n<p>datagen.fit(X)</p>\n\n<p>Now how I get my X_rotated ? </p>\n\n<p>They only explain how to make tricky stuff with epoch and batch I just want to get back my array where each image has randomly rotated nothing more, nothing tricky.\nI don't understand why on tutorials they only explain how to make the tricky stuff but not the basics...</p>\n\n<p><a href=\"https://keras.io/preprocessing/image/\" rel=\"nofollow noreferrer\">https://keras.io/preprocessing/image/</a></p>\n"
        },
        {
            "tags": [
                "python-3.x",
                "gcc",
                "centos",
                "pip"
            ],
            "owner": {
                "reputation": 1,
                "user_id": 5260339,
                "user_type": "registered",
                "profile_image": "https://www.gravatar.com/avatar/153e9def4c49def2be671162e322953f?s=128&d=identicon&r=PG&f=1",
                "display_name": "Григорий Кулин",
                "link": "https://stackoverflow.com/users/5260339/%d0%93%d1%80%d0%b8%d0%b3%d0%be%d1%80%d0%b8%d0%b9-%d0%9a%d1%83%d0%bb%d0%b8%d0%bd"
            },
            "is_answered": false,
            "view_count": 25,
            "answer_count": 1,
            "score": 0,
            "last_activity_date": 1524601029,
            "creation_date": 1524578222,
            "last_edit_date": 1524601029,
            "question_id": 50003562,
            "body_markdown": "I have CentOS 7 with installed mariadb, python3.6 and pip for python3.6  \r\nI also installed glibc-static and libstdc++-static\r\n\r\nI try to install mysqlclient with &quot;pip install mysqlclient&quot;\r\n\r\nI have this error in response:\r\n\r\n     building &#39;_mysql&#39; extension\r\n    creating build/temp.linux-x86_64-3.6\r\n    gcc -pthread -Wno-unused-result -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -Dversion_info=(1,3,12,&#39;final&#39;,0) -D__version__=1.3.12 -I/usr/include/mysql -I/usr/include/python3.6m -c _mysql.c -o build/temp.linux-x86_64-3.6/_mysql.o\r\n    gcc -pthread -shared -Wl,-z,relro build/temp.linux-x86_64-3.6/_mysql.o -L/usr/lib64 -L/usr/lib64 -lmysqlclient -lpthread -lz -lm -ldl -lssl -lcrypto -lpython3.6m -o build/lib.linux-x86_64-3.6/_mysql.cpython-36m-x86_64-linux-gnu.so\r\n    /usr/bin/ld: cannot find -lz\r\n    /usr/bin/ld: cannot find -lssl\r\n    /usr/bin/ld: cannot find -lcrypto\r\n    collect2: error: ld returned 1 exit status\r\n    error: command &#39;gcc&#39; failed with exit status 1\r\n\r\nAnd here full output if it relevant:\r\n\r\n    Collecting mysqlclient\r\n    Using cached\r\n    https://files.pythonhosted.org/packages/6f/86/bad31f1c1bb0cc99e88ca2adb7cb5c71f7a6540c1bb001480513de76a931/mysqlclient-1.3.12.tar.gz\r\n    Installing collected packages: mysqlclient\r\n    Running setup.py install for mysqlclient: started\r\n    Running setup.py install for mysqlclient: finished with status &#39;error&#39;\r\n    Complete output from command /usr/bin/python3.6 -u -c &quot;import setuptools, tokenize;__file__=&#39;/tmp/pip-install-vajbnmgp/mysqlclient/setup.py&#39;;f=getattr(tokenize, &#39;open&#39;, open)(__file__);code=f.read().replace(&#39;\\r\\n&#39;, &#39;\\n&#39;);f.close();exec(compile(code, __file__, &#39;exec&#39;))&quot; install --record /tmp/pip-record-wwcc1x6n/install-record.txt --single-version-externally-managed --compile:\r\n    running install\r\n    running build\r\n    running build_py\r\n    creating build\r\n    creating build/lib.linux-x86_64-3.6\r\n    copying _mysql_exceptions.py -&gt; build/lib.linux-x86_64-3.6\r\n    creating build/lib.linux-x86_64-3.6/MySQLdb\r\n    copying MySQLdb/__init__.py -&gt; build/lib.linux-x86_64-3.6/MySQLdb\r\n    copying MySQLdb/compat.py -&gt; build/lib.linux-x86_64-3.6/MySQLdb\r\n    copying MySQLdb/connections.py -&gt; build/lib.linux-x86_64-3.6/MySQLdb\r\n    copying MySQLdb/converters.py -&gt; build/lib.linux-x86_64-3.6/MySQLdb\r\n    copying MySQLdb/cursors.py -&gt; build/lib.linux-x86_64-3.6/MySQLdb\r\n    copying MySQLdb/release.py -&gt; build/lib.linux-x86_64-3.6/MySQLdb\r\n    copying MySQLdb/times.py -&gt; build/lib.linux-x86_64-3.6/MySQLdb\r\n    creating build/lib.linux-x86_64-3.6/MySQLdb/constants\r\n    copying MySQLdb/constants/__init__.py -&gt; build/lib.linux-x86_64-3.6/MySQLdb/constants\r\n    copying MySQLdb/constants/CLIENT.py -&gt; build/lib.linux-x86_64-3.6/MySQLdb/constants\r\n    copying MySQLdb/constants/CR.py -&gt; build/lib.linux-x86_64-3.6/MySQLdb/constants\r\n    copying MySQLdb/constants/ER.py -&gt; build/lib.linux-x86_64-3.6/MySQLdb/constants\r\n    copying MySQLdb/constants/FIELD_TYPE.py -&gt; build/lib.linux-x86_64-3.6/MySQLdb/constants\r\n    copying MySQLdb/constants/FLAG.py -&gt; build/lib.linux-x86_64-3.6/MySQLdb/constants\r\n    copying MySQLdb/constants/REFRESH.py -&gt; build/lib.linux-x86_64-3.6/MySQLdb/constants\r\n    running build_ext\r\n    building &#39;_mysql&#39; extension\r\n    creating build/temp.linux-x86_64-3.6\r\n    gcc -pthread -Wno-unused-result -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -Dversion_info=(1,3,12,&#39;final&#39;,0) -D__version__=1.3.12 -I/usr/include/mysql -I/usr/include/python3.6m -c _mysql.c -o build/temp.linux-x86_64-3.6/_mysql.o\r\n    gcc -pthread -shared -Wl,-z,relro build/temp.linux-x86_64-3.6/_mysql.o -L/usr/lib64 -L/usr/lib64 -lmysqlclient -lpthread -lz -lm -ldl -lssl -lcrypto -lpython3.6m -o build/lib.linux-x86_64-3.6/_mysql.cpython-36m-x86_64-linux-gnu.so\r\n    /usr/bin/ld: cannot find -lz\r\n    /usr/bin/ld: cannot find -lssl\r\n    /usr/bin/ld: cannot find -lcrypto\r\n    collect2: error: ld returned 1 exit status\r\n    error: command &#39;gcc&#39; failed with exit status 1\r\n\r\n    ----------------------------------------\r\n\r\n**UPDATE**  \r\nI didn&#39;t knew that mariadb is in standard repos and i installed it with this instructions:  \r\nhttps://mariadb.com/kb/en/library/yum/\r\n\r\nWhen I install it from original repos, it just works without problems.",
            "link": "https://stackoverflow.com/questions/50003562/python-compile-error-while-try-install-mysqlclient-package-with-pip-on-centos",
            "title": "python: compile error while try install mysqlclient package with pip on centos",
            "body": "<p>I have CentOS 7 with installed mariadb, python3.6 and pip for python3.6<br>\nI also installed glibc-static and libstdc++-static</p>\n\n<p>I try to install mysqlclient with \"pip install mysqlclient\"</p>\n\n<p>I have this error in response:</p>\n\n<pre><code> building '_mysql' extension\ncreating build/temp.linux-x86_64-3.6\ngcc -pthread -Wno-unused-result -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -Dversion_info=(1,3,12,'final',0) -D__version__=1.3.12 -I/usr/include/mysql -I/usr/include/python3.6m -c _mysql.c -o build/temp.linux-x86_64-3.6/_mysql.o\ngcc -pthread -shared -Wl,-z,relro build/temp.linux-x86_64-3.6/_mysql.o -L/usr/lib64 -L/usr/lib64 -lmysqlclient -lpthread -lz -lm -ldl -lssl -lcrypto -lpython3.6m -o build/lib.linux-x86_64-3.6/_mysql.cpython-36m-x86_64-linux-gnu.so\n/usr/bin/ld: cannot find -lz\n/usr/bin/ld: cannot find -lssl\n/usr/bin/ld: cannot find -lcrypto\ncollect2: error: ld returned 1 exit status\nerror: command 'gcc' failed with exit status 1\n</code></pre>\n\n<p>And here full output if it relevant:</p>\n\n<pre><code>Collecting mysqlclient\nUsing cached\nhttps://files.pythonhosted.org/packages/6f/86/bad31f1c1bb0cc99e88ca2adb7cb5c71f7a6540c1bb001480513de76a931/mysqlclient-1.3.12.tar.gz\nInstalling collected packages: mysqlclient\nRunning setup.py install for mysqlclient: started\nRunning setup.py install for mysqlclient: finished with status 'error'\nComplete output from command /usr/bin/python3.6 -u -c \"import setuptools, tokenize;__file__='/tmp/pip-install-vajbnmgp/mysqlclient/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\\r\\n', '\\n');f.close();exec(compile(code, __file__, 'exec'))\" install --record /tmp/pip-record-wwcc1x6n/install-record.txt --single-version-externally-managed --compile:\nrunning install\nrunning build\nrunning build_py\ncreating build\ncreating build/lib.linux-x86_64-3.6\ncopying _mysql_exceptions.py -&gt; build/lib.linux-x86_64-3.6\ncreating build/lib.linux-x86_64-3.6/MySQLdb\ncopying MySQLdb/__init__.py -&gt; build/lib.linux-x86_64-3.6/MySQLdb\ncopying MySQLdb/compat.py -&gt; build/lib.linux-x86_64-3.6/MySQLdb\ncopying MySQLdb/connections.py -&gt; build/lib.linux-x86_64-3.6/MySQLdb\ncopying MySQLdb/converters.py -&gt; build/lib.linux-x86_64-3.6/MySQLdb\ncopying MySQLdb/cursors.py -&gt; build/lib.linux-x86_64-3.6/MySQLdb\ncopying MySQLdb/release.py -&gt; build/lib.linux-x86_64-3.6/MySQLdb\ncopying MySQLdb/times.py -&gt; build/lib.linux-x86_64-3.6/MySQLdb\ncreating build/lib.linux-x86_64-3.6/MySQLdb/constants\ncopying MySQLdb/constants/__init__.py -&gt; build/lib.linux-x86_64-3.6/MySQLdb/constants\ncopying MySQLdb/constants/CLIENT.py -&gt; build/lib.linux-x86_64-3.6/MySQLdb/constants\ncopying MySQLdb/constants/CR.py -&gt; build/lib.linux-x86_64-3.6/MySQLdb/constants\ncopying MySQLdb/constants/ER.py -&gt; build/lib.linux-x86_64-3.6/MySQLdb/constants\ncopying MySQLdb/constants/FIELD_TYPE.py -&gt; build/lib.linux-x86_64-3.6/MySQLdb/constants\ncopying MySQLdb/constants/FLAG.py -&gt; build/lib.linux-x86_64-3.6/MySQLdb/constants\ncopying MySQLdb/constants/REFRESH.py -&gt; build/lib.linux-x86_64-3.6/MySQLdb/constants\nrunning build_ext\nbuilding '_mysql' extension\ncreating build/temp.linux-x86_64-3.6\ngcc -pthread -Wno-unused-result -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -Dversion_info=(1,3,12,'final',0) -D__version__=1.3.12 -I/usr/include/mysql -I/usr/include/python3.6m -c _mysql.c -o build/temp.linux-x86_64-3.6/_mysql.o\ngcc -pthread -shared -Wl,-z,relro build/temp.linux-x86_64-3.6/_mysql.o -L/usr/lib64 -L/usr/lib64 -lmysqlclient -lpthread -lz -lm -ldl -lssl -lcrypto -lpython3.6m -o build/lib.linux-x86_64-3.6/_mysql.cpython-36m-x86_64-linux-gnu.so\n/usr/bin/ld: cannot find -lz\n/usr/bin/ld: cannot find -lssl\n/usr/bin/ld: cannot find -lcrypto\ncollect2: error: ld returned 1 exit status\nerror: command 'gcc' failed with exit status 1\n\n----------------------------------------\n</code></pre>\n\n<p><strong>UPDATE</strong><br>\nI didn't knew that mariadb is in standard repos and i installed it with this instructions:<br>\n<a href=\"https://mariadb.com/kb/en/library/yum/\" rel=\"nofollow noreferrer\">https://mariadb.com/kb/en/library/yum/</a></p>\n\n<p>When I install it from original repos, it just works without problems.</p>\n"
        },
        {
            "tags": [
                "php",
                "arrays"
            ],
            "owner": {
                "reputation": 7100,
                "user_id": 235771,
                "user_type": "registered",
                "accept_rate": 80,
                "profile_image": "https://www.gravatar.com/avatar/e2ea04c383a954d0a171ddaa3f055442?s=128&d=identicon&r=PG",
                "display_name": "jhchen",
                "link": "https://stackoverflow.com/users/235771/jhchen"
            },
            "is_answered": true,
            "view_count": 23771,
            "accepted_answer_id": 19713361,
            "answer_count": 10,
            "score": 22,
            "last_activity_date": 1524601023,
            "creation_date": 1266504826,
            "question_id": 2289475,
            "body_markdown": "I have an array whose values are all arrays of a specific format that looks like this:\r\n\r\n    Array\r\n    (\r\n        [0] =&gt; Array\r\n               (\r\n                   [username] =&gt; John\r\n               )    \r\n        [1] =&gt; Array\r\n               (\r\n                   [username] =&gt; Joe\r\n               )\r\n        [2] =&gt; Array\r\n               (\r\n                   [username] =&gt; Jake\r\n               )\r\n    )\r\n\r\nand I would like to have this:\r\n    \r\n    Array\r\n    (\r\n        [0] =&gt; John   \r\n        [1] =&gt; Joe\r\n        [2] =&gt; Jake\r\n    )\r\n\r\nI can do this manually with a loop but is there a better way? If not, is it possible to do this for an array of objects that have a common attribute?",
            "link": "https://stackoverflow.com/questions/2289475/converting-php-array-of-arrays-into-single-array",
            "title": "Converting php array of arrays into single array",
            "body": "<p>I have an array whose values are all arrays of a specific format that looks like this:</p>\n\n<pre><code>Array\n(\n    [0] =&gt; Array\n           (\n               [username] =&gt; John\n           )    \n    [1] =&gt; Array\n           (\n               [username] =&gt; Joe\n           )\n    [2] =&gt; Array\n           (\n               [username] =&gt; Jake\n           )\n)\n</code></pre>\n\n<p>and I would like to have this:</p>\n\n<pre><code>Array\n(\n    [0] =&gt; John   \n    [1] =&gt; Joe\n    [2] =&gt; Jake\n)\n</code></pre>\n\n<p>I can do this manually with a loop but is there a better way? If not, is it possible to do this for an array of objects that have a common attribute?</p>\n"
        }
    ],
    "has_more": true,
    "quota_max": 300,
    "quota_remaining": 299
}